// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Case struct {
	ID         uuid.UUID
	Kind       int16
	TargetKind *int16
	TargetID   *uuid.UUID
	Lane       string
	Score      float32
	OpenedAt   *time.Time
	ResolvedAt *time.Time
	ResolvedBy *uuid.UUID
	Outcome    *int16
	Data       json.RawMessage
	CreatedAt  time.Time
}

type Counter struct {
	OwnerID   uuid.UUID
	Seq       int64
	PurgedSeq int64
}

type Deck struct {
	ID            uuid.UUID
	OwnerID       *uuid.UUID
	ParentID      *uuid.UUID
	Name          string
	Position      string
	Icon          *string
	Color         int16
	Description   *string
	Language      *string
	NewPerDay     int16
	ReviewsPerDay int32
	Retention     int16
	Gated         bool
	UnlockAt      int16
	V             int64
	Seq           int64
	DeletedAt     *int64
}

type EmailChange struct {
	UserID    uuid.UUID
	Email     string
	CodeHash  []byte
	Tries     int16
	ExpiresAt time.Time
}

type Event struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SubjectID  uuid.UUID
	Card       int16
	Kind       int16
	Value      *int16
	At         int64
	DurationMs *int32
	Due        *int64
	Stability  *float32
	Difficulty *float32
	Reps       *int16
	Lapses     *int16
	Seq        int64
}

type Invite struct {
	ID        uuid.UUID
	TokenHash []byte
	DeckID    uuid.UUID
	Role      int16
	Email     *string
	CreatedBy uuid.UUID
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Medium struct {
	Hash       []byte
	Size       int32
	Mime       string
	UploadedBy *uuid.UUID
	Verified   bool
	CreatedAt  time.Time
}

type Name struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      int16
	Value     *string
	ActionID  *uuid.UUID
	CreatedAt time.Time
	Undone    bool
}

type NetworkRestriction struct {
	ActionID uuid.UUID
	Range    netip.Prefix
	Until    *time.Time
}

type Note struct {
	ID         uuid.UUID
	OwnerID    *uuid.UUID
	DeckID     uuid.UUID
	TemplateID uuid.UUID
	Fields     json.RawMessage
	SearchText string
	V          int64
	Seq        int64
	DeletedAt  *int64
	Tags       string
}

type NoteMedium struct {
	NoteID uuid.UUID
	Hash   []byte
}

type Notification struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Kind         string
	Presentation int16
	Title        string
	Body         string
	LinkLabel    *string
	LinkUrl      *string
	CreatedAt    time.Time
	SeenAt       *time.Time
}

type PromoCode struct {
	Code      string
	BatchID   uuid.UUID
	RevokedBy *uuid.UUID
}

type Publication struct {
	DeckID      uuid.UUID
	Slug        string
	Listed      bool
	PublishedAt time.Time
	RemovedAt   *time.Time
	RemovedBy   *uuid.UUID
	Name        *string
	Language    *string
	OwnerID     *uuid.UUID
	Gone        bool
	Followers   int32
	Notes       int32
	Hot         int32
	RefreshedAt *time.Time
}

type PushDevice struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Platform   int16
	Endpoint   string
	P256dh     *string
	Auth       *string
	Reminders  bool
	LocalUntil *time.Time
	CreatedAt  time.Time
	LastOkAt   *time.Time
}

type ReminderState struct {
	UserID     uuid.UUID
	LastSentAt *time.Time
	LastSentOn *time.Time
	Ignored    int16
	PausedAt   *time.Time
}

type Report struct {
	ID         uuid.UUID
	ReporterID uuid.UUID
	CaseID     uuid.UUID
	Reason     string
	Law        *string
	Note       *string
	Weight     float32
	CreatedAt  time.Time
}

type Role struct {
	UserID   uuid.UUID
	Role     string
	ActionID uuid.UUID
}

type SecondFactorReset struct {
	UserID    uuid.UUID
	CodeHash  []byte
	Tries     int16
	ExpiresAt time.Time
	DueAt     *time.Time
}

type Setting struct {
	UserID        uuid.UUID
	Grading       int16
	Theme         int16
	TextSize      int16
	Timezone      *string
	FsrsWeights   *string
	V             int64
	Seq           int64
	ReminderAt    *int16
	ReminderEmail *bool
}

type Share struct {
	DeckID    uuid.UUID
	UserID    uuid.UUID
	Role      int16
	CreatedAt time.Time
}

type SmartDeck struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Name          string
	Position      string
	Icon          *string
	Color         int16
	Filter        json.RawMessage
	NewPerDay     int16
	ReviewsPerDay int32
	V             int64
	Seq           int64
	DeletedAt     *int64
}

type StaffAction struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	Kind       string
	UserID     *uuid.UUID
	DeckID     *uuid.UUID
	Reason     *string
	Note       *string
	Until      *time.Time
	Data       json.RawMessage
	CaseID     *uuid.UUID
	CreatedAt  time.Time
	UndoneAt   *time.Time
	UndoneBy   *uuid.UUID
	UndoReason *string
}

type Subscription struct {
	Provider       string
	Ref            string
	UserID         uuid.UUID
	Product        string
	Status         string
	PeriodEnd      *time.Time
	AutoRenew      bool
	Sandbox        bool
	UpdatedAt      time.Time
	RenewalStopped bool
}

type Summary struct {
	UserID  uuid.UUID
	Due     []int32
	Learned int32
	At      time.Time
}

type Template struct {
	ID        uuid.UUID
	OwnerID   *uuid.UUID
	Name      string
	Kind      int16
	Def       json.RawMessage
	V         int64
	Seq       int64
	DeletedAt *int64
}

type User struct {
	ID                 uuid.UUID
	Name               *string
	ProUntil           *time.Time
	StripeCustomer     *string
	CreatedAt          time.Time
	Username           string
	UsernameChangedAt  *time.Time
	Flag               *string
	ActivityHidden     bool
	ProfileConfirmedAt *time.Time
	RestrictedUntil    *time.Time
	BannedUntil        *time.Time
	EmailKey           *string
}

type UserIp struct {
	UserID  uuid.UUID
	Ip      netip.Addr
	FirstAt time.Time
	LastAt  time.Time
	Uses    int32
}
