// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const addNetwork = `-- name: AddNetwork :exec
INSERT INTO network_restrictions (action_id, range, until) VALUES ($1, $2, $3)
`

type AddNetworkParams struct {
	ActionID uuid.UUID
	Range    netip.Prefix
	Until    *time.Time
}

func (q *Queries) AddNetwork(ctx context.Context, arg AddNetworkParams) error {
	_, err := q.db.Exec(ctx, addNetwork, arg.ActionID, arg.Range, arg.Until)
	return err
}

const currentName = `-- name: CurrentName :one
SELECT value, (action_id IS NOT NULL)::boolean AS by_staff FROM names
WHERE user_id = $1 AND kind = $2 AND NOT undone ORDER BY created_at DESC LIMIT 1
`

type CurrentNameParams struct {
	UserID uuid.UUID
	Kind   int16
}

type CurrentNameRow struct {
	Value   *string
	ByStaff bool
}

// The newest name of a kind that isn't undone, and whether staff set it.
func (q *Queries) CurrentName(ctx context.Context, arg CurrentNameParams) (CurrentNameRow, error) {
	row := q.db.QueryRow(ctx, currentName, arg.UserID, arg.Kind)
	var i CurrentNameRow
	err := row.Scan(&i.Value, &i.ByStaff)
	return i, err
}

const deleteShares = `-- name: DeleteShares :exec
DELETE FROM shares WHERE deck_id = $1
`

func (q *Queries) DeleteShares(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShares, deckID)
	return err
}

const deriveNetwork = `-- name: DeriveNetwork :exec
DELETE FROM network_restrictions WHERE action_id = $1
`

func (q *Queries) DeriveNetwork(ctx context.Context, actionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deriveNetwork, actionID)
	return err
}

const derivePublication = `-- name: DerivePublication :exec
UPDATE publications p SET (removed_at, removed_by) = (
  SELECT a.created_at, a.id FROM staff_actions a
  WHERE a.deck_id = p.deck_id AND a.kind = 'deck.remove' AND a.undone_at IS NULL ORDER BY a.id DESC LIMIT 1
) WHERE p.deck_id = $1
`

func (q *Queries) DerivePublication(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.Exec(ctx, derivePublication, deckID)
	return err
}

const deriveStanding = `-- name: DeriveStanding :one
WITH lift AS (
  SELECT max(created_at) AS at FROM staff_actions WHERE user_id = $1 AND kind = 'user.lift' AND undone_at IS NULL
)
UPDATE users u SET
  restricted_until = (SELECT max(coalesce(a.until, '9999-12-31')) FROM staff_actions a, lift
                      WHERE a.user_id = $1 AND a.kind = 'user.restrict' AND a.undone_at IS NULL
                        AND (lift.at IS NULL OR a.created_at > lift.at)),
  banned_until = (SELECT max(coalesce(a.until, '9999-12-31')) FROM staff_actions a, lift
                  WHERE a.user_id = $1 AND a.kind = 'user.ban' AND a.undone_at IS NULL
                    AND (lift.at IS NULL OR a.created_at > lift.at))
WHERE u.id = $1
RETURNING restricted_until, banned_until
`

type DeriveStandingRow struct {
	RestrictedUntil *time.Time
	BannedUntil     *time.Time
}

// Restricted and banned until the latest end of those entries since the last lift, none undone.
func (q *Queries) DeriveStanding(ctx context.Context, userID *uuid.UUID) (DeriveStandingRow, error) {
	row := q.db.QueryRow(ctx, deriveStanding, userID)
	var i DeriveStandingRow
	err := row.Scan(&i.RestrictedUntil, &i.BannedUntil)
	return i, err
}

const forgetOldIPs = `-- name: ForgetOldIPs :exec
DELETE FROM user_ips WHERE last_at < now() - interval '90 days'
`

func (q *Queries) ForgetOldIPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, forgetOldIPs)
	return err
}

const forgetSeenNotifications = `-- name: ForgetSeenNotifications :exec
DELETE FROM notifications WHERE seen_at < now() - interval '90 days' OR (presentation = 0 AND created_at < now() - interval '90 days')
`

func (q *Queries) ForgetSeenNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, forgetSeenNotifications)
	return err
}

const iPsOf = `-- name: IPsOf :many
SELECT ip::text AS ip, first_at, last_at, uses FROM user_ips WHERE user_id = $1 ORDER BY last_at DESC LIMIT 50
`

type IPsOfRow struct {
	Ip      string
	FirstAt time.Time
	LastAt  time.Time
	Uses    int32
}

func (q *Queries) IPsOf(ctx context.Context, userID uuid.UUID) ([]IPsOfRow, error) {
	rows, err := q.db.Query(ctx, iPsOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IPsOfRow{}
	for rows.Next() {
		var i IPsOfRow
		if err := rows.Scan(
			&i.Ip,
			&i.FirstAt,
			&i.LastAt,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ladder = `-- name: Ladder :one
SELECT count(*) FROM staff_actions
WHERE user_id = $1 AND kind IN ('user.warn', 'user.restrict', 'user.ban', 'deck.remove') AND undone_at IS NULL
  AND created_at > now() - interval '180 days'
`

// What someone was warned, restricted or banned for lately: the next step follows from it.
func (q *Queries) Ladder(ctx context.Context, userID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, ladder, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const namesOf = `-- name: NamesOf :many
SELECT kind, value, created_at, (action_id IS NOT NULL)::boolean AS by_staff, undone FROM names
WHERE user_id = $1 ORDER BY created_at DESC LIMIT 100
`

type NamesOfRow struct {
	Kind      int16
	Value     *string
	CreatedAt time.Time
	ByStaff   bool
	Undone    bool
}

func (q *Queries) NamesOf(ctx context.Context, userID uuid.UUID) ([]NamesOfRow, error) {
	rows, err := q.db.Query(ctx, namesOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamesOfRow{}
	for rows.Next() {
		var i NamesOfRow
		if err := rows.Scan(
			&i.Kind,
			&i.Value,
			&i.CreatedAt,
			&i.ByStaff,
			&i.Undone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const networkRestricted = `-- name: NetworkRestricted :one
SELECT EXISTS (SELECT 1 FROM network_restrictions WHERE range >>= $1::inet AND (until IS NULL OR until > now()))
`

func (q *Queries) NetworkRestricted(ctx context.Context, dollar_1 netip.Addr) (bool, error) {
	row := q.db.QueryRow(ctx, networkRestricted, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const relatedByEmail = `-- name: RelatedByEmail :many
SELECT id FROM users WHERE email_key = $1 AND id <> $2 LIMIT 20
`

type RelatedByEmailParams struct {
	EmailKey *string
	ID       uuid.UUID
}

func (q *Queries) RelatedByEmail(ctx context.Context, arg RelatedByEmailParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, relatedByEmail, arg.EmailKey, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedByIP = `-- name: RelatedByIP :many
SELECT other.user_id, count(*)::int AS shared FROM user_ips mine
JOIN user_ips other ON other.user_id <> mine.user_id AND (
  other.ip = mine.ip
  OR (family(mine.ip) = 6 AND family(other.ip) = 6 AND network(set_masklen(other.ip, 64)) = network(set_masklen(mine.ip, 64))))
WHERE mine.user_id = $1
GROUP BY other.user_id ORDER BY 2 DESC LIMIT 20
`

type RelatedByIPRow struct {
	UserID uuid.UUID
	Shared int32
}

// Others seen at the same address (IPv6: the same /64) in the last 90 days.
func (q *Queries) RelatedByIP(ctx context.Context, userID uuid.UUID) ([]RelatedByIPRow, error) {
	rows, err := q.db.Query(ctx, relatedByIP, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelatedByIPRow{}
	for rows.Next() {
		var i RelatedByIPRow
		if err := rows.Scan(&i.UserID, &i.Shared); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedByName = `-- name: RelatedByName :many
SELECT DISTINCT other.user_id FROM names mine
JOIN names other ON other.user_id <> mine.user_id AND other.value % mine.value AND similarity(other.value, mine.value) > 0.6
WHERE mine.user_id = $1 AND mine.value IS NOT NULL AND length(mine.value) >= 4
  AND mine.value !~ '^user[0-9]+$' AND other.value !~ '^user[0-9]+$'
LIMIT 20
`

// Others whose names, now or before, look like any of this person's (Rondo's own usernames aside).
func (q *Queries) RelatedByName(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, relatedByName, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewingSubscriptions = `-- name: RenewingSubscriptions :many
SELECT provider, ref FROM subscriptions WHERE user_id = $1 AND auto_renew AND status IN ('active', 'trialing', 'in_grace')
`

type RenewingSubscriptionsRow struct {
	Provider string
	Ref      string
}

// Someone's store subscriptions that will renew.
func (q *Queries) RenewingSubscriptions(ctx context.Context, userID uuid.UUID) ([]RenewingSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, renewingSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenewingSubscriptionsRow{}
	for rows.Next() {
		var i RenewingSubscriptionsRow
		if err := rows.Scan(&i.Provider, &i.Ref); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key FROM users
WHERE username LIKE lower($1::text) || '%' OR name ILIKE '%' || $1::text || '%' OR id::text = $1::text
ORDER BY (username = lower($1::text)) DESC, created_at DESC LIMIT 30
`

func (q *Queries) SearchUsers(ctx context.Context, q_ string) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProUntil,
			&i.StripeCustomer,
			&i.CreatedAt,
			&i.Username,
			&i.UsernameChangedAt,
			&i.Flag,
			&i.ActivityHidden,
			&i.ProfileConfirmedAt,
			&i.RestrictedUntil,
			&i.BannedUntil,
			&i.EmailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seen = `-- name: Seen :exec
INSERT INTO user_ips (user_id, ip) VALUES ($1, $2)
ON CONFLICT (user_id, ip) DO UPDATE SET last_at = now(), uses = user_ips.uses + 1
`

type SeenParams struct {
	UserID uuid.UUID
	Ip     netip.Addr
}

// Where someone is: every social action counts.
func (q *Queries) Seen(ctx context.Context, arg SeenParams) error {
	_, err := q.db.Exec(ctx, seen, arg.UserID, arg.Ip)
	return err
}

const seenHourly = `-- name: SeenHourly :exec
INSERT INTO user_ips (user_id, ip) VALUES ($1, $2)
ON CONFLICT (user_id, ip) DO UPDATE SET last_at = now(), uses = user_ips.uses + 1
WHERE user_ips.last_at < now() - interval '1 hour'
`

type SeenHourlyParams struct {
	UserID uuid.UUID
	Ip     netip.Addr
}

// The same for opening the app, at most once an hour per address.
func (q *Queries) SeenHourly(ctx context.Context, arg SeenHourlyParams) error {
	_, err := q.db.Exec(ctx, seenHourly, arg.UserID, arg.Ip)
	return err
}

const setEmailKey = `-- name: SetEmailKey :exec
UPDATE users SET email_key = $2 WHERE id = $1 AND email_key IS DISTINCT FROM $2
`

type SetEmailKeyParams struct {
	ID       uuid.UUID
	EmailKey *string
}

func (q *Queries) SetEmailKey(ctx context.Context, arg SetEmailKeyParams) error {
	_, err := q.db.Exec(ctx, setEmailKey, arg.ID, arg.EmailKey)
	return err
}

const setNames = `-- name: SetNames :exec
UPDATE users SET username = $2, name = $3, username_changed_at = $4 WHERE id = $1
`

type SetNamesParams struct {
	ID                uuid.UUID
	Username          string
	Name              *string
	UsernameChangedAt *time.Time
}

func (q *Queries) SetNames(ctx context.Context, arg SetNamesParams) error {
	_, err := q.db.Exec(ctx, setNames,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.UsernameChangedAt,
	)
	return err
}

const setRenewalStopped = `-- name: SetRenewalStopped :exec
UPDATE subscriptions SET renewal_stopped = $3 WHERE provider = $1 AND ref = $2
`

type SetRenewalStoppedParams struct {
	Provider       string
	Ref            string
	RenewalStopped bool
}

func (q *Queries) SetRenewalStopped(ctx context.Context, arg SetRenewalStoppedParams) error {
	_, err := q.db.Exec(ctx, setRenewalStopped, arg.Provider, arg.Ref, arg.RenewalStopped)
	return err
}

const sharesOf = `-- name: SharesOf :many
SELECT user_id, role FROM shares WHERE deck_id = $1
`

type SharesOfRow struct {
	UserID uuid.UUID
	Role   int16
}

func (q *Queries) SharesOf(ctx context.Context, deckID uuid.UUID) ([]SharesOfRow, error) {
	rows, err := q.db.Query(ctx, sharesOf, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharesOfRow{}
	for rows.Next() {
		var i SharesOfRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stoppedRenewals = `-- name: StoppedRenewals :many
SELECT provider, ref, user_id, product, status, period_end, auto_renew, sandbox, updated_at, renewal_stopped FROM subscriptions WHERE user_id = $1 AND renewal_stopped
`

// Someone's subscriptions whose renewal a ban turned off.
func (q *Queries) StoppedRenewals(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, stoppedRenewals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Provider,
			&i.Ref,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.PeriodEnd,
			&i.AutoRenew,
			&i.Sandbox,
			&i.UpdatedAt,
			&i.RenewalStopped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undoNames = `-- name: UndoNames :exec
UPDATE names SET undone = true WHERE action_id = $1
`

func (q *Queries) UndoNames(ctx context.Context, actionID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, undoNames, actionID)
	return err
}

const usersAt = `-- name: UsersAt :many
SELECT DISTINCT u.id, u.name, u.pro_until, u.stripe_customer, u.created_at, u.username, u.username_changed_at, u.flag, u.activity_hidden, u.profile_confirmed_at, u.restricted_until, u.banned_until, u.email_key FROM users u JOIN user_ips i ON i.user_id = u.id WHERE i.ip <<= $1::cidr LIMIT 30
`

func (q *Queries) UsersAt(ctx context.Context, range_ netip.Prefix) ([]User, error) {
	rows, err := q.db.Query(ctx, usersAt, range_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProUntil,
			&i.StripeCustomer,
			&i.CreatedAt,
			&i.Username,
			&i.UsernameChangedAt,
			&i.Flag,
			&i.ActivityHidden,
			&i.ProfileConfirmedAt,
			&i.RestrictedUntil,
			&i.BannedUntil,
			&i.EmailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByID = `-- name: UsersByID :many
SELECT id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key FROM users WHERE id = ANY($1::uuid[])
`

func (q *Queries) UsersByID(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, usersByID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProUntil,
			&i.StripeCustomer,
			&i.CreatedAt,
			&i.Username,
			&i.UsernameChangedAt,
			&i.Flag,
			&i.ActivityHidden,
			&i.ProfileConfirmedAt,
			&i.RestrictedUntil,
			&i.BannedUntil,
			&i.EmailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
