// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addName = `-- name: AddName :exec
INSERT INTO names (id, user_id, kind, value, action_id) VALUES ($1, $2, $3, $4, $5)
`

type AddNameParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Kind     int16
	Value    *string
	ActionID *uuid.UUID
}

func (q *Queries) AddName(ctx context.Context, arg AddNameParams) error {
	_, err := q.db.Exec(ctx, addName,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Value,
		arg.ActionID,
	)
	return err
}

const movedUsername = `-- name: MovedUsername :one
SELECT u.username FROM names n JOIN users u ON u.id = n.user_id
WHERE n.kind = 1 AND n.value = $1 AND NOT n.undone AND u.username <> $1
  AND EXISTS (SELECT 1 FROM names m WHERE m.user_id = n.user_id AND m.kind = 1 AND NOT m.undone
              AND m.created_at > n.created_at AND m.created_at > now() - interval '30 days')
ORDER BY n.created_at DESC LIMIT 1
`

// Where an old username went: its last holder's username now, when they changed it in the last 30 days.
func (q *Queries) MovedUsername(ctx context.Context, value *string) (string, error) {
	row := q.db.QueryRow(ctx, movedUsername, value)
	var username string
	err := row.Scan(&username)
	return username, err
}

const reviewDays = `-- name: ReviewDays :many
SELECT (to_timestamp(e.at / 1000.0) AT TIME ZONE $1::text - interval '4 hours')::date AS day,
  count(*)::int AS reviews, coalesce(sum(e.duration_ms), 0)::bigint AS ms
FROM events e
WHERE e.user_id = $2 AND e.kind = 1
  AND NOT EXISTS (SELECT 1 FROM events v WHERE v.user_id = e.user_id AND v.kind = 8 AND v.subject_id = e.id)
GROUP BY 1 ORDER BY 1
`

type ReviewDaysParams struct {
	Zone   string
	UserID uuid.UUID
}

type ReviewDaysRow struct {
	Day     time.Time
	Reviews int32
	Ms      int64
}

// Days with reviews, in the learner's time zone with days starting at 4 am, without undone answers.
func (q *Queries) ReviewDays(ctx context.Context, arg ReviewDaysParams) ([]ReviewDaysRow, error) {
	rows, err := q.db.Query(ctx, reviewDays, arg.Zone, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewDaysRow{}
	for rows.Next() {
		var i ReviewDaysRow
		if err := rows.Scan(&i.Day, &i.Reviews, &i.Ms); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProfile = `-- name: SetProfile :one
UPDATE users SET username = $2, username_changed_at = $3, name = $4, flag = $5, activity_hidden = $6,
  profile_confirmed_at = coalesce(profile_confirmed_at, $7)
WHERE id = $1 RETURNING id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key
`

type SetProfileParams struct {
	ID                 uuid.UUID
	Username           string
	UsernameChangedAt  *time.Time
	Name               *string
	Flag               *string
	ActivityHidden     bool
	ProfileConfirmedAt *time.Time
}

func (q *Queries) SetProfile(ctx context.Context, arg SetProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, setProfile,
		arg.ID,
		arg.Username,
		arg.UsernameChangedAt,
		arg.Name,
		arg.Flag,
		arg.ActivityHidden,
		arg.ProfileConfirmedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProUntil,
		&i.StripeCustomer,
		&i.CreatedAt,
		&i.Username,
		&i.UsernameChangedAt,
		&i.Flag,
		&i.ActivityHidden,
		&i.ProfileConfirmedAt,
		&i.RestrictedUntil,
		&i.BannedUntil,
		&i.EmailKey,
	)
	return i, err
}

const timezone = `-- name: Timezone :one
SELECT timezone FROM settings WHERE user_id = $1
`

func (q *Queries) Timezone(ctx context.Context, userID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, timezone, userID)
	var timezone *string
	err := row.Scan(&timezone)
	return timezone, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key FROM users WHERE username = $1
`

func (q *Queries) UserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProUntil,
		&i.StripeCustomer,
		&i.CreatedAt,
		&i.Username,
		&i.UsernameChangedAt,
		&i.Flag,
		&i.ActivityHidden,
		&i.ProfileConfirmedAt,
		&i.RestrictedUntil,
		&i.BannedUntil,
		&i.EmailKey,
	)
	return i, err
}

const usernameHeld = `-- name: UsernameHeld :one
SELECT EXISTS (
  SELECT 1 FROM names n WHERE n.kind = 1 AND n.value = $1 AND n.user_id <> $2 AND NOT n.undone
    AND EXISTS (SELECT 1 FROM names m WHERE m.user_id = n.user_id AND m.kind = 1 AND NOT m.undone
                AND m.created_at > n.created_at AND m.created_at > now() - interval '30 days')
)
`

type UsernameHeldParams struct {
	Value  *string
	UserID uuid.UUID
}

// Someone else's username until less than 30 days ago stays theirs.
func (q *Queries) UsernameHeld(ctx context.Context, arg UsernameHeldParams) (bool, error) {
	row := q.db.QueryRow(ctx, usernameHeld, arg.Value, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
