// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promo.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addGrant = `-- name: AddGrant :execrows
INSERT INTO subscriptions (provider, ref, user_id, product, status, period_end, auto_renew, sandbox)
VALUES ($1, $2, $3, 'pro', 'active', $4, false, false) ON CONFLICT DO NOTHING
`

type AddGrantParams struct {
	Provider  string
	Ref       string
	UserID    uuid.UUID
	PeriodEnd *time.Time
}

// Pro that isn't bought: from staff ("grant") or a code ("promo").
func (q *Queries) AddGrant(ctx context.Context, arg AddGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGrant,
		arg.Provider,
		arg.Ref,
		arg.UserID,
		arg.PeriodEnd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addPromoCode = `-- name: AddPromoCode :exec
INSERT INTO promo_codes (code, batch_id) VALUES ($1, $2)
`

type AddPromoCodeParams struct {
	Code    string
	BatchID uuid.UUID
}

func (q *Queries) AddPromoCode(ctx context.Context, arg AddPromoCodeParams) error {
	_, err := q.db.Exec(ctx, addPromoCode, arg.Code, arg.BatchID)
	return err
}

const batchCodes = `-- name: BatchCodes :many
SELECT c.code, s.user_id AS used_by, s.updated_at AS used_at, (c.revoked_by IS NOT NULL AND r.undone_at IS NULL)::boolean AS revoked
FROM promo_codes c
LEFT JOIN subscriptions s ON s.provider = 'promo' AND s.ref = c.code
LEFT JOIN staff_actions r ON r.id = c.revoked_by
WHERE c.batch_id = $1 ORDER BY c.code
`

type BatchCodesRow struct {
	Code    string
	UsedBy  *uuid.UUID
	UsedAt  *time.Time
	Revoked bool
}

func (q *Queries) BatchCodes(ctx context.Context, batchID uuid.UUID) ([]BatchCodesRow, error) {
	rows, err := q.db.Query(ctx, batchCodes, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchCodesRow{}
	for rows.Next() {
		var i BatchCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.UsedBy,
			&i.UsedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoBatches = `-- name: PromoBatches :many
SELECT b.id, b.actor_id, b.kind, b.user_id, b.deck_id, b.reason, b.note, b.until, b.data, b.case_id, b.created_at, b.undone_at, b.undone_by, b.undo_reason, (SELECT count(*) FROM promo_codes c WHERE c.batch_id = b.id)::int AS codes,
  (SELECT count(*) FROM promo_codes c JOIN subscriptions s ON s.provider = 'promo' AND s.ref = c.code WHERE c.batch_id = b.id)::int AS used
FROM staff_actions b WHERE b.kind = 'promo.batch' ORDER BY b.id DESC LIMIT 100
`

type PromoBatchesRow struct {
	ID         uuid.UUID
	ActorID    *uuid.UUID
	Kind       string
	UserID     *uuid.UUID
	DeckID     *uuid.UUID
	Reason     *string
	Note       *string
	Until      *time.Time
	Data       json.RawMessage
	CaseID     *uuid.UUID
	CreatedAt  time.Time
	UndoneAt   *time.Time
	UndoneBy   *uuid.UUID
	UndoReason *string
	Codes      int32
	Used       int32
}

func (q *Queries) PromoBatches(ctx context.Context) ([]PromoBatchesRow, error) {
	rows, err := q.db.Query(ctx, promoBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoBatchesRow{}
	for rows.Next() {
		var i PromoBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.UserID,
			&i.DeckID,
			&i.Reason,
			&i.Note,
			&i.Until,
			&i.Data,
			&i.CaseID,
			&i.CreatedAt,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoReason,
			&i.Codes,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoCode = `-- name: PromoCode :one
SELECT c.code, b.until AS redeem_by, b.data, (b.undone_at IS NOT NULL)::boolean AS batch_undone,
  (c.revoked_by IS NOT NULL AND r.undone_at IS NULL)::boolean AS revoked
FROM promo_codes c JOIN staff_actions b ON b.id = c.batch_id LEFT JOIN staff_actions r ON r.id = c.revoked_by
WHERE c.code = $1
`

type PromoCodeRow struct {
	Code        string
	RedeemBy    *time.Time
	Data        json.RawMessage
	BatchUndone bool
	Revoked     bool
}

func (q *Queries) PromoCode(ctx context.Context, code string) (PromoCodeRow, error) {
	row := q.db.QueryRow(ctx, promoCode, code)
	var i PromoCodeRow
	err := row.Scan(
		&i.Code,
		&i.RedeemBy,
		&i.Data,
		&i.BatchUndone,
		&i.Revoked,
	)
	return i, err
}

const redemption = `-- name: Redemption :one
SELECT provider, ref, user_id, product, status, period_end, auto_renew, sandbox, updated_at, renewal_stopped FROM subscriptions WHERE provider = 'promo' AND ref = $1
`

func (q *Queries) Redemption(ctx context.Context, ref string) (Subscription, error) {
	row := q.db.QueryRow(ctx, redemption, ref)
	var i Subscription
	err := row.Scan(
		&i.Provider,
		&i.Ref,
		&i.UserID,
		&i.Product,
		&i.Status,
		&i.PeriodEnd,
		&i.AutoRenew,
		&i.Sandbox,
		&i.UpdatedAt,
		&i.RenewalStopped,
	)
	return i, err
}

const renewing = `-- name: Renewing :one
SELECT EXISTS (
  SELECT 1 FROM subscriptions WHERE user_id = $1 AND provider NOT IN ('promo', 'grant') AND auto_renew
    AND status IN ('active', 'trialing', 'in_grace')
)
`

// Whether someone pays for Pro through a store and it renews.
func (q *Queries) Renewing(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, renewing, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeCode = `-- name: RevokeCode :exec
UPDATE promo_codes SET revoked_by = $2 WHERE code = $1
`

type RevokeCodeParams struct {
	Code      string
	RevokedBy *uuid.UUID
}

func (q *Queries) RevokeCode(ctx context.Context, arg RevokeCodeParams) error {
	_, err := q.db.Exec(ctx, revokeCode, arg.Code, arg.RevokedBy)
	return err
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :exec
UPDATE subscriptions SET status = $3, updated_at = now() WHERE provider = $1 AND ref = $2
`

type SetSubscriptionStatusParams struct {
	Provider string
	Ref      string
	Status   string
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionStatus, arg.Provider, arg.Ref, arg.Status)
	return err
}

const unrevokeCode = `-- name: UnrevokeCode :exec
UPDATE promo_codes SET revoked_by = NULL WHERE code = $1 AND revoked_by = $2
`

type UnrevokeCodeParams struct {
	Code      string
	RevokedBy *uuid.UUID
}

func (q *Queries) UnrevokeCode(ctx context.Context, arg UnrevokeCodeParams) error {
	_, err := q.db.Exec(ctx, unrevokeCode, arg.Code, arg.RevokedBy)
	return err
}
