// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reminders.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePushDevice = `-- name: DeletePushDevice :exec
DELETE FROM push_devices WHERE id = $1 AND user_id = $2
`

type DeletePushDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePushDevice(ctx context.Context, arg DeletePushDeviceParams) error {
	_, err := q.db.Exec(ctx, deletePushDevice, arg.ID, arg.UserID)
	return err
}

const forgetPushDevice = `-- name: ForgetPushDevice :exec
DELETE FROM push_devices WHERE id = $1
`

func (q *Queries) ForgetPushDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forgetPushDevice, id)
	return err
}

const pushDevices = `-- name: PushDevices :many
SELECT id, user_id, platform, endpoint, p256dh, auth, reminders, local_until, created_at, last_ok_at FROM push_devices WHERE user_id = $1
`

func (q *Queries) PushDevices(ctx context.Context, userID uuid.UUID) ([]PushDevice, error) {
	rows, err := q.db.Query(ctx, pushDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDevice{}
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.Reminders,
			&i.LocalUntil,
			&i.CreatedAt,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushOK = `-- name: PushOK :exec
UPDATE push_devices SET last_ok_at = now() WHERE id = $1
`

func (q *Queries) PushOK(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, pushOK, id)
	return err
}

const putPushDevice = `-- name: PutPushDevice :one
INSERT INTO push_devices (id, user_id, platform, endpoint, p256dh, auth, reminders, local_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (endpoint) DO UPDATE SET user_id = EXCLUDED.user_id, p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth,
  reminders = EXCLUDED.reminders, local_until = EXCLUDED.local_until
RETURNING id, user_id, platform, endpoint, p256dh, auth, reminders, local_until, created_at, last_ok_at
`

type PutPushDeviceParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Platform   int16
	Endpoint   string
	P256dh     *string
	Auth       *string
	Reminders  bool
	LocalUntil *time.Time
}

func (q *Queries) PutPushDevice(ctx context.Context, arg PutPushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRow(ctx, putPushDevice,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.Reminders,
		arg.LocalUntil,
	)
	var i PushDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.Reminders,
		&i.LocalUntil,
		&i.CreatedAt,
		&i.LastOkAt,
	)
	return i, err
}

const putReminderState = `-- name: PutReminderState :exec
INSERT INTO reminder_state (user_id, last_sent_at, last_sent_on, ignored, paused_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET last_sent_at = EXCLUDED.last_sent_at, last_sent_on = EXCLUDED.last_sent_on,
  ignored = EXCLUDED.ignored, paused_at = EXCLUDED.paused_at
`

type PutReminderStateParams struct {
	UserID     uuid.UUID
	LastSentAt *time.Time
	LastSentOn *time.Time
	Ignored    int16
	PausedAt   *time.Time
}

func (q *Queries) PutReminderState(ctx context.Context, arg PutReminderStateParams) error {
	_, err := q.db.Exec(ctx, putReminderState,
		arg.UserID,
		arg.LastSentAt,
		arg.LastSentOn,
		arg.Ignored,
		arg.PausedAt,
	)
	return err
}

const putSummary = `-- name: PutSummary :exec
INSERT INTO summaries (user_id, due, learned) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET due = EXCLUDED.due, learned = EXCLUDED.learned, at = now()
`

type PutSummaryParams struct {
	UserID  uuid.UUID
	Due     []int32
	Learned int32
}

func (q *Queries) PutSummary(ctx context.Context, arg PutSummaryParams) error {
	_, err := q.db.Exec(ctx, putSummary, arg.UserID, arg.Due, arg.Learned)
	return err
}

const reminding = `-- name: Reminding :many
SELECT s.user_id, s.reminder_at, coalesce(s.reminder_email, false)::boolean AS email, s.timezone,
  r.last_sent_at, r.last_sent_on, coalesce(r.ignored, 0)::smallint AS ignored, r.paused_at,
  coalesce((SELECT max(e.at) FROM events e WHERE e.user_id = s.user_id AND e.kind = 1), 0)::bigint AS last_review
FROM settings s LEFT JOIN reminder_state r ON r.user_id = s.user_id
WHERE s.reminder_at IS NOT NULL
`

type RemindingRow struct {
	UserID     uuid.UUID
	ReminderAt *int16
	Email      bool
	Timezone   *string
	LastSentAt *time.Time
	LastSentOn *time.Time
	Ignored    int16
	PausedAt   *time.Time
	LastReview int64
}

// Everyone with reminders on, and what the server knows to decide whether to remind them now.
func (q *Queries) Reminding(ctx context.Context) ([]RemindingRow, error) {
	rows, err := q.db.Query(ctx, reminding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemindingRow{}
	for rows.Next() {
		var i RemindingRow
		if err := rows.Scan(
			&i.UserID,
			&i.ReminderAt,
			&i.Email,
			&i.Timezone,
			&i.LastSentAt,
			&i.LastSentOn,
			&i.Ignored,
			&i.PausedAt,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summary = `-- name: Summary :one
SELECT user_id, due, learned, at FROM summaries WHERE user_id = $1
`

func (q *Queries) Summary(ctx context.Context, userID uuid.UUID) (Summary, error) {
	row := q.db.QueryRow(ctx, summary, userID)
	var i Summary
	err := row.Scan(
		&i.UserID,
		&i.Due,
		&i.Learned,
		&i.At,
	)
	return i, err
}
