// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const addCase = `-- name: AddCase :one
INSERT INTO cases (id, kind, target_kind, target_id, lane, opened_at, data) VALUES ($1, $2, $3, $4, $5, now(), $6)
RETURNING id, kind, target_kind, target_id, lane, score, opened_at, resolved_at, resolved_by, outcome, data, created_at
`

type AddCaseParams struct {
	ID         uuid.UUID
	Kind       int16
	TargetKind *int16
	TargetID   *uuid.UUID
	Lane       string
	Data       json.RawMessage
}

func (q *Queries) AddCase(ctx context.Context, arg AddCaseParams) (Case, error) {
	row := q.db.QueryRow(ctx, addCase,
		arg.ID,
		arg.Kind,
		arg.TargetKind,
		arg.TargetID,
		arg.Lane,
		arg.Data,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.TargetID,
		&i.Lane,
		&i.Score,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Outcome,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const addReport = `-- name: AddReport :execrows
INSERT INTO reports (id, reporter_id, case_id, reason, law, note, weight) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (reporter_id, case_id) DO NOTHING
`

type AddReportParams struct {
	ID         uuid.UUID
	ReporterID uuid.UUID
	CaseID     uuid.UUID
	Reason     string
	Law        *string
	Note       *string
	Weight     float32
}

func (q *Queries) AddReport(ctx context.Context, arg AddReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReport,
		arg.ID,
		arg.ReporterID,
		arg.CaseID,
		arg.Reason,
		arg.Law,
		arg.Note,
		arg.Weight,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const caseByID = `-- name: CaseByID :one
SELECT id, kind, target_kind, target_id, lane, score, opened_at, resolved_at, resolved_by, outcome, data, created_at FROM cases WHERE id = $1
`

func (q *Queries) CaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRow(ctx, caseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.TargetID,
		&i.Lane,
		&i.Score,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Outcome,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const caseReporters = `-- name: CaseReporters :many
SELECT DISTINCT reporter_id FROM reports WHERE case_id = $1
`

func (q *Queries) CaseReporters(ctx context.Context, caseID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, caseReporters, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reporter_id uuid.UUID
		if err := rows.Scan(&reporter_id); err != nil {
			return nil, err
		}
		items = append(items, reporter_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseReports = `-- name: CaseReports :many
SELECT id, reporter_id, case_id, reason, law, note, weight, created_at FROM reports WHERE case_id = $1 ORDER BY id
`

func (q *Queries) CaseReports(ctx context.Context, caseID uuid.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, caseReports, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.CaseID,
			&i.Reason,
			&i.Law,
			&i.Note,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deckBrief = `-- name: DeckBrief :one
SELECT d.id, d.name, d.owner_id, p.slug FROM decks d LEFT JOIN publications p ON p.deck_id = d.id WHERE d.id = $1
`

type DeckBriefRow struct {
	ID      uuid.UUID
	Name    string
	OwnerID *uuid.UUID
	Slug    *string
}

func (q *Queries) DeckBrief(ctx context.Context, id uuid.UUID) (DeckBriefRow, error) {
	row := q.db.QueryRow(ctx, deckBrief, id)
	var i DeckBriefRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Slug,
	)
	return i, err
}

const deriveCase = `-- name: DeriveCase :one
UPDATE cases c SET (resolved_at, resolved_by, outcome) = (
  SELECT a.created_at, a.actor_id, (CASE WHEN a.kind = 'case.dismiss' THEN 2 ELSE 1 END)::smallint
  FROM staff_actions a WHERE a.case_id = c.id AND a.undone_at IS NULL ORDER BY a.id LIMIT 1
)
WHERE c.id = $1
RETURNING c.id, c.kind, c.target_kind, c.target_id, c.lane, c.score, c.opened_at, c.resolved_at, c.resolved_by, c.outcome, c.data, c.created_at
`

// Resolved by the first staff action with the case that isn't undone: dismissed, or acted on.
func (q *Queries) DeriveCase(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRow(ctx, deriveCase, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.TargetID,
		&i.Lane,
		&i.Score,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Outcome,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const followers = `-- name: Followers :one
SELECT count(*)::int FROM shares WHERE deck_id = $1
`

func (q *Queries) Followers(ctx context.Context, deckID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, followers, deckID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const openCases = `-- name: OpenCases :many
SELECT c.id, c.kind, c.target_kind, c.target_id, c.lane, c.score, c.opened_at, c.resolved_at, c.resolved_by, c.outcome, c.data, c.created_at, (SELECT count(*) FROM reports r WHERE r.case_id = c.id)::int AS reports,
  coalesce((SELECT array_agg(DISTINCT r.reason) FROM reports r WHERE r.case_id = c.id), '{}')::text[] AS reasons
FROM cases c
WHERE c.opened_at IS NOT NULL AND c.resolved_at IS NULL
  AND ($1::text IS NULL OR c.lane = $1)
  AND ($2::smallint IS NULL OR c.target_kind = $2)
ORDER BY array_position(ARRAY['illegal', 'safety', 'spam', 'other', 'waves', 'flags'], c.lane), c.score DESC, c.opened_at
LIMIT 100
`

type OpenCasesParams struct {
	Lane   *string
	Target *int16
}

type OpenCasesRow struct {
	ID         uuid.UUID
	Kind       int16
	TargetKind *int16
	TargetID   *uuid.UUID
	Lane       string
	Score      float32
	OpenedAt   *time.Time
	ResolvedAt *time.Time
	ResolvedBy *uuid.UUID
	Outcome    *int16
	Data       json.RawMessage
	CreatedAt  time.Time
	Reports    int32
	Reasons    []string
}

func (q *Queries) OpenCases(ctx context.Context, arg OpenCasesParams) ([]OpenCasesRow, error) {
	rows, err := q.db.Query(ctx, openCases, arg.Lane, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenCasesRow{}
	for rows.Next() {
		var i OpenCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TargetKind,
			&i.TargetID,
			&i.Lane,
			&i.Score,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Outcome,
			&i.Data,
			&i.CreatedAt,
			&i.Reports,
			&i.Reasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openFlag = `-- name: OpenFlag :one
SELECT EXISTS (SELECT 1 FROM cases WHERE kind = 3 AND target_kind = $1 AND target_id = $2 AND resolved_at IS NULL)
`

type OpenFlagParams struct {
	TargetKind *int16
	TargetID   *uuid.UUID
}

func (q *Queries) OpenFlag(ctx context.Context, arg OpenFlagParams) (bool, error) {
	row := q.db.QueryRow(ctx, openFlag, arg.TargetKind, arg.TargetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publishedBy = `-- name: PublishedBy :one
SELECT count(*)::int FROM publications p JOIN decks d ON d.id = p.deck_id
WHERE d.owner_id = $1 AND p.published_at > now() - interval '24 hours'
`

// Decks someone published in the last 24 hours.
func (q *Queries) PublishedBy(ctx context.Context, ownerID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, publishedBy, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const publishedFrom = `-- name: PublishedFrom :one
SELECT count(*)::int FROM publications p JOIN decks d ON d.id = p.deck_id
WHERE p.published_at > now() - interval '24 hours' AND d.owner_id IN (SELECT user_id FROM user_ips WHERE ip = $1)
`

// Decks published in the last 24 hours by people seen at an address.
func (q *Queries) PublishedFrom(ctx context.Context, ip netip.Addr) (int32, error) {
	row := q.db.QueryRow(ctx, publishedFrom, ip)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const publishedLately = `-- name: PublishedLately :many
SELECT p.deck_id FROM publications p WHERE p.published_at > now() - interval '24 hours' ORDER BY p.published_at DESC LIMIT 25
`

func (q *Queries) PublishedLately(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, publishedLately)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var deck_id uuid.UUID
		if err := rows.Scan(&deck_id); err != nil {
			return nil, err
		}
		items = append(items, deck_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportedLately = `-- name: ReportedLately :many
SELECT c.target_kind, c.target_id, count(*)::int AS reports FROM reports r JOIN cases c ON c.id = r.case_id
WHERE r.created_at > now() - interval '24 hours' AND c.kind = 1
GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 25
`

type ReportedLatelyRow struct {
	TargetKind *int16
	TargetID   *uuid.UUID
	Reports    int32
}

func (q *Queries) ReportedLately(ctx context.Context) ([]ReportedLatelyRow, error) {
	rows, err := q.db.Query(ctx, reportedLately)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportedLatelyRow{}
	for rows.Next() {
		var i ReportedLatelyRow
		if err := rows.Scan(&i.TargetKind, &i.TargetID, &i.Reports); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reporterRecord = `-- name: ReporterRecord :one
SELECT count(*) FILTER (WHERE c.outcome = 1)::int AS upheld, count(*) FILTER (WHERE c.resolved_at IS NOT NULL)::int AS resolved
FROM reports r JOIN cases c ON c.id = r.case_id WHERE r.reporter_id = $1
`

type ReporterRecordRow struct {
	Upheld   int32
	Resolved int32
}

// How a reporter's earlier reports went: how many led to action, of those resolved.
func (q *Queries) ReporterRecord(ctx context.Context, reporterID uuid.UUID) (ReporterRecordRow, error) {
	row := q.db.QueryRow(ctx, reporterRecord, reporterID)
	var i ReporterRecordRow
	err := row.Scan(&i.Upheld, &i.Resolved)
	return i, err
}

const reportersLately = `-- name: ReportersLately :many
SELECT r.reporter_id, count(*)::int AS reports FROM reports r
WHERE r.created_at > now() - interval '24 hours' GROUP BY 1 ORDER BY 2 DESC LIMIT 25
`

type ReportersLatelyRow struct {
	ReporterID uuid.UUID
	Reports    int32
}

func (q *Queries) ReportersLately(ctx context.Context) ([]ReportersLatelyRow, error) {
	rows, err := q.db.Query(ctx, reportersLately)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportersLatelyRow{}
	for rows.Next() {
		var i ReportersLatelyRow
		if err := rows.Scan(&i.ReporterID, &i.Reports); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportsCase = `-- name: ReportsCase :one
WITH made AS (
  INSERT INTO cases (id, kind, target_kind, target_id, lane) VALUES ($1, 1, $2, $3, 'other')
  ON CONFLICT (target_kind, target_id) WHERE kind = 1 AND resolved_at IS NULL DO NOTHING
  RETURNING id, kind, target_kind, target_id, lane, score, opened_at, resolved_at, resolved_by, outcome, data, created_at
)
SELECT id, kind, target_kind, target_id, lane, score, opened_at, resolved_at, resolved_by, outcome, data, created_at FROM made
UNION ALL
SELECT id, kind, target_kind, target_id, lane, score, opened_at, resolved_at, resolved_by, outcome, data, created_at FROM cases WHERE kind = 1 AND target_kind = $2 AND target_id = $3 AND resolved_at IS NULL
LIMIT 1
`

type ReportsCaseParams struct {
	ID         uuid.UUID
	TargetKind *int16
	TargetID   *uuid.UUID
}

type ReportsCaseRow struct {
	ID         uuid.UUID
	Kind       int16
	TargetKind *int16
	TargetID   *uuid.UUID
	Lane       string
	Score      float32
	OpenedAt   *time.Time
	ResolvedAt *time.Time
	ResolvedBy *uuid.UUID
	Outcome    *int16
	Data       json.RawMessage
	CreatedAt  time.Time
}

// The unresolved reports case about a target, made when there's none.
func (q *Queries) ReportsCase(ctx context.Context, arg ReportsCaseParams) (ReportsCaseRow, error) {
	row := q.db.QueryRow(ctx, reportsCase, arg.ID, arg.TargetKind, arg.TargetID)
	var i ReportsCaseRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.TargetID,
		&i.Lane,
		&i.Score,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Outcome,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const reportsLately = `-- name: ReportsLately :one
SELECT count(*)::int FROM reports WHERE reporter_id = $1 AND created_at > now() - interval '24 hours'
`

func (q *Queries) ReportsLately(ctx context.Context, reporterID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, reportsLately, reporterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const scoreCase = `-- name: ScoreCase :one
UPDATE cases c SET score = s.total, lane = s.lane,
  opened_at = coalesce(c.opened_at, CASE WHEN s.total >= $1::real OR s.lane = 'illegal' THEN now() END)
FROM (
  SELECT sum(weight)::real AS total,
    (ARRAY['illegal', 'safety', 'spam', 'other'])[min(CASE reason WHEN 'illegal' THEN 1 WHEN 'spam' THEN 3 WHEN 'other' THEN 4 ELSE 2 END)] AS lane
  FROM reports WHERE case_id = $2
) s
WHERE c.id = $2
RETURNING c.id, c.kind, c.target_kind, c.target_id, c.lane, c.score, c.opened_at, c.resolved_at, c.resolved_by, c.outcome, c.data, c.created_at
`

type ScoreCaseParams struct {
	Threshold float32
	ID        uuid.UUID
}

// A case's weight and lane from its reports; it opens to staff past the threshold, or at once for
// illegal content.
func (q *Queries) ScoreCase(ctx context.Context, arg ScoreCaseParams) (Case, error) {
	row := q.db.QueryRow(ctx, scoreCase, arg.Threshold, arg.ID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.TargetID,
		&i.Lane,
		&i.Score,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Outcome,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const waveLately = `-- name: WaveLately :one
SELECT EXISTS (SELECT 1 FROM cases WHERE kind = 2 AND data->>'metric' = $1::text AND created_at > now() - interval '24 hours')
`

func (q *Queries) WaveLately(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, waveLately, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const windows = `-- name: Windows :many
SELECT
  (SELECT count(*) FROM reports r WHERE r.created_at >= w AND r.created_at < w + interval '1 day')::int AS reports,
  (SELECT count(*) FROM publications p WHERE p.published_at >= w AND p.published_at < w + interval '1 day')::int AS publications,
  (SELECT count(*) FROM users u WHERE u.created_at >= w AND u.created_at < w + interval '1 day')::int AS signups
FROM generate_series(now() - interval '29 days', now() - interval '1 day', interval '1 day') w
ORDER BY w
`

type WindowsRow struct {
	Reports      int32
	Publications int32
	Signups      int32
}

// Reports, publications and new accounts in each of the last 29 days (24-hour windows, the latest
// last).
func (q *Queries) Windows(ctx context.Context) ([]WindowsRow, error) {
	rows, err := q.db.Query(ctx, windows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WindowsRow{}
	for rows.Next() {
		var i WindowsRow
		if err := rows.Scan(&i.Reports, &i.Publications, &i.Signups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
