// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rondo.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMedia = `-- name: AddMedia :exec
INSERT INTO media (hash, size, mime, uploaded_by) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type AddMediaParams struct {
	Hash       []byte
	Size       int32
	Mime       string
	UploadedBy *uuid.UUID
}

func (q *Queries) AddMedia(ctx context.Context, arg AddMediaParams) error {
	_, err := q.db.Exec(ctx, addMedia,
		arg.Hash,
		arg.Size,
		arg.Mime,
		arg.UploadedBy,
	)
	return err
}

const addShare = `-- name: AddShare :exec
INSERT INTO shares (deck_id, user_id, role) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddShareParams struct {
	DeckID uuid.UUID
	UserID uuid.UUID
	Role   int16
}

func (q *Queries) AddShare(ctx context.Context, arg AddShareParams) error {
	_, err := q.db.Exec(ctx, addShare, arg.DeckID, arg.UserID, arg.Role)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, token_hash, deck_id, role, email, created_by, expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInviteParams struct {
	ID        uuid.UUID
	TokenHash []byte
	DeckID    uuid.UUID
	Role      int16
	Email     *string
	CreatedBy uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.ID,
		arg.TokenHash,
		arg.DeckID,
		arg.Role,
		arg.Email,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const deck = `-- name: Deck :one
SELECT id, owner_id, name, description, language, icon, color, deleted_at FROM decks WHERE id = $1
`

type DeckRow struct {
	ID          uuid.UUID
	OwnerID     *uuid.UUID
	Name        string
	Description *string
	Language    *string
	Icon        *string
	Color       int16
	DeletedAt   *int64
}

func (q *Queries) Deck(ctx context.Context, id uuid.UUID) (DeckRow, error) {
	row := q.db.QueryRow(ctx, deck, id)
	var i DeckRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Language,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE hash = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, deleteMedia, hash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const ensureUser = `-- name: EnsureUser :execrows
WITH added AS (
  INSERT INTO users (id, username) VALUES ($2, $3) ON CONFLICT DO NOTHING
  RETURNING id, username, created_at
)
INSERT INTO names (id, user_id, kind, value, created_at) SELECT $1, id, 1, username, created_at FROM added
`

type EnsureUserParams struct {
	NameID   uuid.UUID
	ID       uuid.UUID
	Username string
}

// A new account gets the username Rondo picked for it, recorded in its names.
func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureUser, arg.NameID, arg.ID, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invite = `-- name: Invite :one
SELECT id, token_hash, deck_id, role, email, created_by, expires_at, used_at FROM invites WHERE id = $1
`

func (q *Queries) Invite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, invite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DeckID,
		&i.Role,
		&i.Email,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const inviteByHash = `-- name: InviteByHash :one
SELECT id, token_hash, deck_id, role, email, created_by, expires_at, used_at FROM invites WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) InviteByHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, inviteByHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.DeckID,
		&i.Role,
		&i.Email,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const invites = `-- name: Invites :many
SELECT id, token_hash, deck_id, role, email, created_by, expires_at, used_at FROM invites WHERE deck_id = $1 AND used_at IS NULL AND expires_at > now() ORDER BY expires_at
`

func (q *Queries) Invites(ctx context.Context, deckID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, invites, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.DeckID,
			&i.Role,
			&i.Email,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lending = `-- name: Lending :many
SELECT s.deck_id FROM shares s JOIN decks d ON d.id = s.deck_id WHERE d.owner_id = $1
UNION
SELECT i.deck_id FROM invites i JOIN decks d ON d.id = i.deck_id
WHERE d.owner_id = $1 AND i.used_at IS NULL AND i.expires_at > now()
`

// An owner's decks that others borrow (followers included) or have a pending invitation to.
func (q *Queries) Lending(ctx context.Context, ownerID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lending, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var deck_id uuid.UUID
		if err := rows.Scan(&deck_id); err != nil {
			return nil, err
		}
		items = append(items, deck_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const media = `-- name: Media :one
SELECT hash, size, mime, uploaded_by, verified, created_at FROM media WHERE hash = $1
`

func (q *Queries) Media(ctx context.Context, hash []byte) (Medium, error) {
	row := q.db.QueryRow(ctx, media, hash)
	var i Medium
	err := row.Scan(
		&i.Hash,
		&i.Size,
		&i.Mime,
		&i.UploadedBy,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const mediaUsage = `-- name: MediaUsage :one
SELECT coalesce(sum(m.size), 0)::bigint FROM media m
WHERE m.hash IN (SELECT nm.hash FROM note_media nm JOIN notes n ON n.id = nm.note_id WHERE n.owner_id = $1)
`

func (q *Queries) MediaUsage(ctx context.Context, ownerID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, mediaUsage, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ownMedia = `-- name: OwnMedia :many
SELECT DISTINCT nm.hash FROM note_media nm JOIN notes n ON n.id = nm.note_id WHERE n.owner_id = $1
`

func (q *Queries) OwnMedia(ctx context.Context, ownerID *uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, ownMedia, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var hash []byte
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publication = `-- name: Publication :one
SELECT p.deck_id, p.slug, p.listed, p.published_at, p.removed_at, p.removed_by, p.name, p.language, p.owner_id, p.gone, p.followers, p.notes, p.hot, p.refreshed_at, (SELECT count(*) FROM shares s WHERE s.deck_id = p.deck_id) AS followers FROM publications p WHERE p.deck_id = $1
`

type PublicationRow struct {
	DeckID      uuid.UUID
	Slug        string
	Listed      bool
	PublishedAt time.Time
	RemovedAt   *time.Time
	RemovedBy   *uuid.UUID
	Name        *string
	Language    *string
	OwnerID     *uuid.UUID
	Gone        bool
	Followers   int32
	Notes       int32
	Hot         int32
	RefreshedAt *time.Time
	Followers_2 int64
}

func (q *Queries) Publication(ctx context.Context, deckID uuid.UUID) (PublicationRow, error) {
	row := q.db.QueryRow(ctx, publication, deckID)
	var i PublicationRow
	err := row.Scan(
		&i.DeckID,
		&i.Slug,
		&i.Listed,
		&i.PublishedAt,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.Name,
		&i.Language,
		&i.OwnerID,
		&i.Gone,
		&i.Followers,
		&i.Notes,
		&i.Hot,
		&i.RefreshedAt,
		&i.Followers_2,
	)
	return i, err
}

const publicationBySlug = `-- name: PublicationBySlug :one
SELECT deck_id, slug, listed, published_at, removed_at, removed_by, name, language, owner_id, gone, followers, notes, hot, refreshed_at FROM publications WHERE slug = $1 AND listed AND removed_at IS NULL
`

func (q *Queries) PublicationBySlug(ctx context.Context, slug string) (Publication, error) {
	row := q.db.QueryRow(ctx, publicationBySlug, slug)
	var i Publication
	err := row.Scan(
		&i.DeckID,
		&i.Slug,
		&i.Listed,
		&i.PublishedAt,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.Name,
		&i.Language,
		&i.OwnerID,
		&i.Gone,
		&i.Followers,
		&i.Notes,
		&i.Hot,
		&i.RefreshedAt,
	)
	return i, err
}

const publish = `-- name: Publish :exec
INSERT INTO publications (deck_id, slug, listed) VALUES ($1, $2, true) ON CONFLICT (deck_id) DO UPDATE SET listed = true
`

type PublishParams struct {
	DeckID uuid.UUID
	Slug   string
}

func (q *Queries) Publish(ctx context.Context, arg PublishParams) error {
	_, err := q.db.Exec(ctx, publish, arg.DeckID, arg.Slug)
	return err
}

const putShare = `-- name: PutShare :exec
INSERT INTO shares (deck_id, user_id, role) VALUES ($1, $2, $3) ON CONFLICT (deck_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type PutShareParams struct {
	DeckID uuid.UUID
	UserID uuid.UUID
	Role   int16
}

func (q *Queries) PutShare(ctx context.Context, arg PutShareParams) error {
	_, err := q.db.Exec(ctx, putShare, arg.DeckID, arg.UserID, arg.Role)
	return err
}

const putSubscription = `-- name: PutSubscription :exec
INSERT INTO subscriptions (provider, ref, user_id, product, status, period_end, auto_renew, sandbox, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (provider, ref) DO UPDATE SET user_id = EXCLUDED.user_id, product = EXCLUDED.product, status = EXCLUDED.status,
  period_end = EXCLUDED.period_end, auto_renew = EXCLUDED.auto_renew, sandbox = EXCLUDED.sandbox, updated_at = now()
`

type PutSubscriptionParams struct {
	Provider  string
	Ref       string
	UserID    uuid.UUID
	Product   string
	Status    string
	PeriodEnd *time.Time
	AutoRenew bool
	Sandbox   bool
}

func (q *Queries) PutSubscription(ctx context.Context, arg PutSubscriptionParams) error {
	_, err := q.db.Exec(ctx, putSubscription,
		arg.Provider,
		arg.Ref,
		arg.UserID,
		arg.Product,
		arg.Status,
		arg.PeriodEnd,
		arg.AutoRenew,
		arg.Sandbox,
	)
	return err
}

const refreshPublications = `-- name: RefreshPublications :exec
WITH RECURSIVE tree AS (
  SELECT p.deck_id AS root, p.deck_id AS id FROM publications p
  WHERE p.listed AND ($1::uuid IS NULL OR p.deck_id = $1)
  UNION
  SELECT tree.root, c.id FROM decks c JOIN tree ON c.parent_id = tree.id WHERE c.deleted_at IS NULL
), counts AS (
  SELECT tree.root, count(n.id)::int AS notes FROM tree LEFT JOIN notes n ON n.deck_id = tree.id AND n.deleted_at IS NULL
  GROUP BY tree.root
)
UPDATE publications p SET
  name = d.name, language = d.language, owner_id = d.owner_id, gone = d.deleted_at IS NOT NULL OR d.owner_id IS NULL,
  followers = (SELECT count(*) FROM shares s WHERE s.deck_id = p.deck_id),
  hot = (SELECT count(*) FROM shares s WHERE s.deck_id = p.deck_id AND s.created_at > now() - interval '7 days'),
  notes = counts.notes,
  refreshed_at = now()
FROM decks d, counts
WHERE d.id = p.deck_id AND counts.root = p.deck_id
`

// Discover's copy of each listing (or one, [deck]): its deck's name, language and author, and counts.
func (q *Queries) RefreshPublications(ctx context.Context, deck *uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshPublications, deck)
	return err
}

const removeShare = `-- name: RemoveShare :exec
DELETE FROM shares WHERE deck_id = $1 AND user_id = $2
`

type RemoveShareParams struct {
	DeckID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveShare(ctx context.Context, arg RemoveShareParams) error {
	_, err := q.db.Exec(ctx, removeShare, arg.DeckID, arg.UserID)
	return err
}

const samples = `-- name: Samples :many
WITH RECURSIVE sub AS (SELECT x.id FROM decks x WHERE x.id = $1 UNION SELECT c.id FROM decks c JOIN sub ON c.parent_id = sub.id WHERE c.deleted_at IS NULL)
SELECT (to_jsonb(n) - 'seq' - 'search_text')::text FROM notes n WHERE n.deck_id IN (SELECT id FROM sub) AND n.deleted_at IS NULL ORDER BY n.id LIMIT 5
`

func (q *Queries) Samples(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, samples, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setName = `-- name: SetName :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key
`

type SetNameParams struct {
	ID   uuid.UUID
	Name *string
}

func (q *Queries) SetName(ctx context.Context, arg SetNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProUntil,
		&i.StripeCustomer,
		&i.CreatedAt,
		&i.Username,
		&i.UsernameChangedAt,
		&i.Flag,
		&i.ActivityHidden,
		&i.ProfileConfirmedAt,
		&i.RestrictedUntil,
		&i.BannedUntil,
		&i.EmailKey,
	)
	return i, err
}

const setProUntil = `-- name: SetProUntil :exec
UPDATE users SET pro_until = $2 WHERE id = $1
`

type SetProUntilParams struct {
	ID       uuid.UUID
	ProUntil *time.Time
}

func (q *Queries) SetProUntil(ctx context.Context, arg SetProUntilParams) error {
	_, err := q.db.Exec(ctx, setProUntil, arg.ID, arg.ProUntil)
	return err
}

const setStripeCustomer = `-- name: SetStripeCustomer :exec
UPDATE users SET stripe_customer = $2 WHERE id = $1
`

type SetStripeCustomerParams struct {
	ID             uuid.UUID
	StripeCustomer *string
}

func (q *Queries) SetStripeCustomer(ctx context.Context, arg SetStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, setStripeCustomer, arg.ID, arg.StripeCustomer)
	return err
}

const shares = `-- name: Shares :many
SELECT s.user_id, s.role, u.name, u.username FROM shares s JOIN users u ON u.id = s.user_id WHERE s.deck_id = $1 ORDER BY s.created_at
`

type SharesRow struct {
	UserID   uuid.UUID
	Role     int16
	Name     *string
	Username string
}

func (q *Queries) Shares(ctx context.Context, deckID uuid.UUID) ([]SharesRow, error) {
	rows, err := q.db.Query(ctx, shares, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharesRow{}
	for rows.Next() {
		var i SharesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Name,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptions = `-- name: Subscriptions :many
SELECT provider, ref, user_id, product, status, period_end, auto_renew, sandbox, updated_at, renewal_stopped FROM subscriptions WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) Subscriptions(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, subscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Provider,
			&i.Ref,
			&i.UserID,
			&i.Product,
			&i.Status,
			&i.PeriodEnd,
			&i.AutoRenew,
			&i.Sandbox,
			&i.UpdatedAt,
			&i.RenewalStopped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtree = `-- name: Subtree :many
WITH RECURSIVE sub AS (SELECT x.id FROM decks x WHERE x.id = $1 UNION SELECT c.id FROM decks c JOIN sub ON c.parent_id = sub.id WHERE c.deleted_at IS NULL)
SELECT (to_jsonb(d) - 'seq')::text FROM decks d WHERE d.id IN (SELECT id FROM sub)
`

func (q *Queries) Subtree(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, subtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const templatesByID = `-- name: TemplatesByID :many
SELECT (to_jsonb(t) - 'seq')::text FROM templates t WHERE t.id = ANY($1::uuid[])
`

func (q *Queries) TemplatesByID(ctx context.Context, dollar_1 []uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, templatesByID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpublish = `-- name: Unpublish :exec
UPDATE publications SET listed = false WHERE deck_id = $1
`

func (q *Queries) Unpublish(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unpublish, deckID)
	return err
}

const unusedMedia = `-- name: UnusedMedia :many
SELECT hash FROM media m WHERE created_at < $1 AND NOT EXISTS (SELECT 1 FROM note_media nm WHERE nm.hash = m.hash) LIMIT 1000
`

func (q *Queries) UnusedMedia(ctx context.Context, createdAt time.Time) ([][]byte, error) {
	rows, err := q.db.Query(ctx, unusedMedia, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var hash []byte
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useInvite = `-- name: UseInvite :exec
UPDATE invites SET used_at = now() WHERE id = $1
`

func (q *Queries) UseInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, useInvite, id)
	return err
}

const user = `-- name: User :one
SELECT id, name, pro_until, stripe_customer, created_at, username, username_changed_at, flag, activity_hidden, profile_confirmed_at, restricted_until, banned_until, email_key FROM users WHERE id = $1
`

func (q *Queries) User(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, user, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProUntil,
		&i.StripeCustomer,
		&i.CreatedAt,
		&i.Username,
		&i.UsernameChangedAt,
		&i.Flag,
		&i.ActivityHidden,
		&i.ProfileConfirmedAt,
		&i.RestrictedUntil,
		&i.BannedUntil,
		&i.EmailKey,
	)
	return i, err
}

const verifyMedia = `-- name: VerifyMedia :exec
UPDATE media SET verified = true WHERE hash = $1
`

func (q *Queries) VerifyMedia(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, verifyMedia, hash)
	return err
}
