// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const emailChange = `-- name: EmailChange :one
SELECT user_id, email, code_hash, tries, expires_at FROM email_changes WHERE user_id = $1
`

func (q *Queries) EmailChange(ctx context.Context, userID uuid.UUID) (EmailChange, error) {
	row := q.db.QueryRow(ctx, emailChange, userID)
	var i EmailChange
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.CodeHash,
		&i.Tries,
		&i.ExpiresAt,
	)
	return i, err
}

const endEmailChange = `-- name: EndEmailChange :exec
DELETE FROM email_changes WHERE user_id = $1
`

func (q *Queries) EndEmailChange(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, endEmailChange, userID)
	return err
}

const endReset = `-- name: EndReset :exec
DELETE FROM second_factor_resets WHERE user_id = $1
`

func (q *Queries) EndReset(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, endReset, userID)
	return err
}

const reset = `-- name: Reset :one
SELECT user_id, code_hash, tries, expires_at, due_at FROM second_factor_resets WHERE user_id = $1
`

func (q *Queries) Reset(ctx context.Context, userID uuid.UUID) (SecondFactorReset, error) {
	row := q.db.QueryRow(ctx, reset, userID)
	var i SecondFactorReset
	err := row.Scan(
		&i.UserID,
		&i.CodeHash,
		&i.Tries,
		&i.ExpiresAt,
		&i.DueAt,
	)
	return i, err
}

const scheduleReset = `-- name: ScheduleReset :exec
UPDATE second_factor_resets SET due_at = $2 WHERE user_id = $1
`

type ScheduleResetParams struct {
	UserID uuid.UUID
	DueAt  *time.Time
}

func (q *Queries) ScheduleReset(ctx context.Context, arg ScheduleResetParams) error {
	_, err := q.db.Exec(ctx, scheduleReset, arg.UserID, arg.DueAt)
	return err
}

const startEmailChange = `-- name: StartEmailChange :exec
INSERT INTO email_changes (user_id, email, code_hash, expires_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET email = EXCLUDED.email, code_hash = EXCLUDED.code_hash, tries = 0, expires_at = EXCLUDED.expires_at
`

type StartEmailChangeParams struct {
	UserID    uuid.UUID
	Email     string
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) StartEmailChange(ctx context.Context, arg StartEmailChangeParams) error {
	_, err := q.db.Exec(ctx, startEmailChange,
		arg.UserID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const startReset = `-- name: StartReset :exec
INSERT INTO second_factor_resets (user_id, code_hash, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET code_hash = EXCLUDED.code_hash, tries = 0, expires_at = EXCLUDED.expires_at
WHERE second_factor_resets.due_at IS NULL
`

type StartResetParams struct {
	UserID    uuid.UUID
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) StartReset(ctx context.Context, arg StartResetParams) error {
	_, err := q.db.Exec(ctx, startReset, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const tryEmailChange = `-- name: TryEmailChange :exec
UPDATE email_changes SET tries = tries + 1 WHERE user_id = $1
`

func (q *Queries) TryEmailChange(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, tryEmailChange, userID)
	return err
}

const tryReset = `-- name: TryReset :exec
UPDATE second_factor_resets SET tries = tries + 1 WHERE user_id = $1
`

func (q *Queries) TryReset(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, tryReset, userID)
	return err
}
