// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const action = `-- name: Action :one
SELECT id, actor_id, kind, user_id, deck_id, reason, note, until, data, case_id, created_at, undone_at, undone_by, undo_reason FROM staff_actions WHERE id = $1
`

func (q *Queries) Action(ctx context.Context, id uuid.UUID) (StaffAction, error) {
	row := q.db.QueryRow(ctx, action, id)
	var i StaffAction
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Kind,
		&i.UserID,
		&i.DeckID,
		&i.Reason,
		&i.Note,
		&i.Until,
		&i.Data,
		&i.CaseID,
		&i.CreatedAt,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoReason,
	)
	return i, err
}

const actionLog = `-- name: ActionLog :many
SELECT id, actor_id, kind, user_id, deck_id, reason, note, until, data, case_id, created_at, undone_at, undone_by, undo_reason FROM staff_actions
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::uuid IS NULL OR deck_id = $3)
  AND ($4::text IS NULL OR kind = $4)
  AND ($5::uuid IS NULL OR id < $5)
ORDER BY id DESC LIMIT 51
`

type ActionLogParams struct {
	Actor  *uuid.UUID
	Target *uuid.UUID
	Deck   *uuid.UUID
	Kind   *string
	Before *uuid.UUID
}

func (q *Queries) ActionLog(ctx context.Context, arg ActionLogParams) ([]StaffAction, error) {
	rows, err := q.db.Query(ctx, actionLog,
		arg.Actor,
		arg.Target,
		arg.Deck,
		arg.Kind,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffAction{}
	for rows.Next() {
		var i StaffAction
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.UserID,
			&i.DeckID,
			&i.Reason,
			&i.Note,
			&i.Until,
			&i.Data,
			&i.CaseID,
			&i.CreatedAt,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actionsSince = `-- name: ActionsSince :many
SELECT id, actor_id, kind, user_id, deck_id, reason, note, until, data, case_id, created_at, undone_at, undone_by, undo_reason FROM staff_actions WHERE actor_id = $1 AND created_at >= $2 AND undone_at IS NULL ORDER BY id DESC
`

type ActionsSinceParams struct {
	ActorID   *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) ActionsSince(ctx context.Context, arg ActionsSinceParams) ([]StaffAction, error) {
	rows, err := q.db.Query(ctx, actionsSince, arg.ActorID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffAction{}
	for rows.Next() {
		var i StaffAction
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Kind,
			&i.UserID,
			&i.DeckID,
			&i.Reason,
			&i.Note,
			&i.Until,
			&i.Data,
			&i.CaseID,
			&i.CreatedAt,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.UndoReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRoles = `-- name: ClearRoles :exec
DELETE FROM roles WHERE user_id = $1
`

func (q *Queries) ClearRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRoles, userID)
	return err
}

const countRecentActions = `-- name: CountRecentActions :one
SELECT count(*) FROM staff_actions WHERE actor_id = $1 AND kind = $2 AND created_at > $3
`

type CountRecentActionsParams struct {
	ActorID   *uuid.UUID
	Kind      string
	CreatedAt time.Time
}

// What an actor did lately, for the hourly limits.
func (q *Queries) CountRecentActions(ctx context.Context, arg CountRecentActionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentActions, arg.ActorID, arg.Kind, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentUndos = `-- name: CountRecentUndos :one
SELECT count(*) FROM staff_actions WHERE undone_by = $1 AND undone_at > $2
`

type CountRecentUndosParams struct {
	UndoneBy *uuid.UUID
	UndoneAt *time.Time
}

func (q *Queries) CountRecentUndos(ctx context.Context, arg CountRecentUndosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentUndos, arg.UndoneBy, arg.UndoneAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deriveRoles = `-- name: DeriveRoles :exec
INSERT INTO roles (user_id, role, action_id)
SELECT $1, latest.role, latest.id FROM (
  SELECT DISTINCT ON (a.data->>'role') a.id, a.kind, a.data->>'role' AS role
  FROM staff_actions a
  WHERE a.user_id = $1 AND a.kind IN ('role.grant', 'role.revoke') AND a.undone_at IS NULL
  ORDER BY a.data->>'role', a.id DESC
) latest WHERE latest.kind = 'role.grant'
`

// A role is held when the newest entry about it, not undone, grants it.
func (q *Queries) DeriveRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deriveRoles, userID)
	return err
}

const frozen = `-- name: Frozen :one
SELECT EXISTS (SELECT 1 FROM staff_actions WHERE user_id = $1 AND kind = 'staff.freeze' AND undone_at IS NULL)
`

// Frozen by the hourly limits until someone undoes the freeze.
func (q *Queries) Frozen(ctx context.Context, userID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, frozen, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAction = `-- name: InsertAction :one
INSERT INTO staff_actions (id, actor_id, kind, user_id, deck_id, reason, note, until, data, case_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, actor_id, kind, user_id, deck_id, reason, note, until, data, case_id, created_at, undone_at, undone_by, undo_reason
`

type InsertActionParams struct {
	ID      uuid.UUID
	ActorID *uuid.UUID
	Kind    string
	UserID  *uuid.UUID
	DeckID  *uuid.UUID
	Reason  *string
	Note    *string
	Until   *time.Time
	Data    json.RawMessage
	CaseID  *uuid.UUID
}

func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (StaffAction, error) {
	row := q.db.QueryRow(ctx, insertAction,
		arg.ID,
		arg.ActorID,
		arg.Kind,
		arg.UserID,
		arg.DeckID,
		arg.Reason,
		arg.Note,
		arg.Until,
		arg.Data,
		arg.CaseID,
	)
	var i StaffAction
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Kind,
		&i.UserID,
		&i.DeckID,
		&i.Reason,
		&i.Note,
		&i.Until,
		&i.Data,
		&i.CaseID,
		&i.CreatedAt,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.UndoReason,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (id, user_id, kind, presentation, title, body, link_label, link_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertNotificationParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Kind         string
	Presentation int16
	Title        string
	Body         string
	LinkLabel    *string
	LinkUrl      *string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Presentation,
		arg.Title,
		arg.Body,
		arg.LinkLabel,
		arg.LinkUrl,
	)
	return err
}

const markSeen = `-- name: MarkSeen :execrows
UPDATE notifications SET seen_at = now() WHERE id = $1 AND user_id = $2 AND seen_at IS NULL
`

type MarkSeenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkSeen(ctx context.Context, arg MarkSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSeen, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUndone = `-- name: MarkUndone :execrows
UPDATE staff_actions SET undone_at = now(), undone_by = $2, undo_reason = $3 WHERE id = $1 AND undone_at IS NULL
`

type MarkUndoneParams struct {
	ID         uuid.UUID
	UndoneBy   *uuid.UUID
	UndoReason *string
}

func (q *Queries) MarkUndone(ctx context.Context, arg MarkUndoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUndone, arg.ID, arg.UndoneBy, arg.UndoReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rolesOf = `-- name: RolesOf :many
SELECT role FROM roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) RolesOf(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rolesOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const team = `-- name: Team :many
SELECT user_id, array_agg(role ORDER BY role)::text[] AS roles FROM roles GROUP BY user_id
`

type TeamRow struct {
	UserID uuid.UUID
	Roles  []string
}

func (q *Queries) Team(ctx context.Context) ([]TeamRow, error) {
	rows, err := q.db.Query(ctx, team)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamRow{}
	for rows.Next() {
		var i TeamRow
		if err := rows.Scan(&i.UserID, &i.Roles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unseenNotifications = `-- name: UnseenNotifications :many
SELECT id, user_id, kind, presentation, title, body, link_label, link_url, created_at, seen_at FROM notifications WHERE user_id = $1 AND seen_at IS NULL AND presentation > 0 ORDER BY id LIMIT 20
`

func (q *Queries) UnseenNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, unseenNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Presentation,
			&i.Title,
			&i.Body,
			&i.LinkLabel,
			&i.LinkUrl,
			&i.CreatedAt,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userRefs = `-- name: UserRefs :many
SELECT id, name, username, flag FROM users WHERE id = ANY($1::uuid[])
`

type UserRefsRow struct {
	ID       uuid.UUID
	Name     *string
	Username string
	Flag     *string
}

func (q *Queries) UserRefs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserRefsRow, error) {
	rows, err := q.db.Query(ctx, userRefs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRefsRow{}
	for rows.Next() {
		var i UserRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Flag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
