package app.rondo.client

import kotlin.js.JsExport
import kotlin.math.roundToLong

/** Every word the apps show, by key. English only for now; a language is another instance. */
@JsExport
open class Strings {
    // Navigation and app-wide
    open val appName = "Rondo"
    open val decks = "Decks"
    open val browse = "Browse"
    open val discover = "Discover"
    open val insights = "Progress"
    open val home = "Home"
    open val settings = "Settings"
    open val templates = "Note types"
    open val importDeck = "Import"
    open val signIn = "Sign in"
    open val signOut = "Sign out"
    open val cancel = "Cancel"
    open val save = "Save"
    open val done = "Done"
    open val delete = "Delete"
    open val restore = "Restore"
    open val rename = "Rename"
    open val copy = "Copy"
    open val moveTo = "Move to…"
    open val topLevel = "Top level"
    open val undo = "Undo"
    open val retry = "Try again"
    open val more = "More"
    open val back = "Back"
    open val moveUp = "Move up"
    open val moveDown = "Move down"
    open val edit = "Edit"
    open val add = "Add"
    open val close = "Close"
    open val loading = "Loading…"
    open val search = "Search"
    open val none = "None"
    open val syncNow = "Sync now"
    open val syncing = "Syncing…"
    open val synced = "Synced"
    open val syncIssues = "Sync issues"
    open val otherTab = "Rondo is open in another tab"
    open val otherTabHint = "It works in one tab at a time, so your cards stay in sync. Use it here instead?"
    open val useHere = "Use Rondo here"
    open val notFound = "Nothing here"
    open val notFoundHint = "This page doesn't exist, or it moved."
    open val goHome = "Go home"
    open val expand = "Expand"
    open val collapse = "Collapse"
    open val move = "Move"
    open val open = "Open"
    open val showMore = "Show more"
    open val signOutTitle = "Sign out?"
    open val signOutAnyway = "Sign out anyway"
    fun unsynced(n: Int) = (if (n == 1) "1 change hasn't" else "$n changes haven't") +
        " reached the server yet. Signing out now discards them."
    fun issues(n: Int) = if (n == 1) "1 change couldn't sync." else "$n changes couldn't sync."
    open val pro = "Pro"
    open val free = "Free"
    open val select = "Select"
    open val deselect = "Deselect"
    open val lower = "Lower"
    open val raise = "Raise"

    // Sync banners
    open val offline = "You're offline. Changes stay on this device until you're back."
    open val signedOutSync = "Sign in to sync your decks across devices."
    open val outdated = "This version of Rondo is too old to sync. Update to continue."
    open val clock = "Your device's clock is off, so syncing paused. Set the time automatically."
    open val syncFailed = "Syncing didn't work. Rondo will try again."

    // Home
    open val yourDecks = "Your decks"
    open val sharedWithYou = "Shared with you"
    open val recentlyDeleted = "Recently deleted"
    open val deletedNote = "Kept for 30 days, then removed for good."
    open val newDeck = "New deck"
    open val newSubdeck = "New sub-deck"
    open val deckName = "Name"
    open val study = "Study"
    open val studyAll = "Study all"
    open val homeEmpty = "What will you learn next?"
    open val homeEmptyHint = "Create a deck for something you want to remember."
    open val createFirstDeck = "Create your first deck"
    open val keepGoing = "Keep going"
    open val readyToday = "Ready when you are"
    open val doneToday = "Well done!"
    open val nothingDue = "Nothing due right now"
    open val thisWeek = "This week"
    open val importDecks = "Import from Anki"
    open val discoverDecks = "Discover decks"
    open val emptyDeck = "Empty: open it to add notes"
    open val namePlaceholder = "Name, like Spanish or Anatomy"
    open val createDeck = "Create deck"
    open val emoji = "Emoji"
    open val noEmoji = "No emoji"
    open val noColor = "No color"
    open val browseDeck = "Browse notes"
    open val moveQuestion = "Move this deck?"
    open val locked = "Locked"
    open val removedByAuthor = "Removed by its author. You can still study it, or copy it."
    open val leave = "Leave"
    open val convert = "Convert to Rondo format"
    open val convertHint = "Makes an editable copy; your progress comes along."
    fun levelOf(index: Int, of: Int) = "Level $index of $of"
    fun sharedBy(name: String?) = if (name == null) "Shared with you" else "From $name"
    fun opened(name: String) = "$name is open now"
    fun due(n: Int) = if (n == 1) "1 card due" else "$n cards due"
    fun tomorrow(n: Int) = when (n) {
        0 -> "Nothing due tomorrow. Come back any time."
        1 -> "Tomorrow: 1 review."
        else -> "Tomorrow: $n reviews."
    }
    fun answers(n: Int) = if (n == 1) "1 answer" else "$n answers"
    fun answerWord(n: Int) = if (n == 1) "answer" else "answers"
    fun toStudy(due: Int, notes: Int) = (if (due > 0) "$due to study · " else "") + this.notes(notes)
    fun opensAfter(deck: String) = "Opens once “$deck” is learned"
    fun moveOut(deck: String, from: String) =
        "“$deck” leaves “$from”. People who borrow “$from” lose access to it and its cards."
    fun colorName(n: Int) =
        listOf(noColor, "Red", "Orange", "Yellow", "Green", "Blue", "Purple", "Pink").getOrElse(n) { "" }

    // Deck
    open val deckSettings = "Deck settings"
    open val description = "Description"
    open val language = "Language"
    open val color = "Color"
    open val newPerDay = "New cards a day"
    open val reviewsPerDay = "Reviews a day"
    open val retention = "Target retention"
    open val levels = "Levels"
    open val levelsHint = "Sub-decks open one after another, as you learn the ones before."
    open val unlockAt = "Opens after"
    open val unlockNow = "Open now"
    open val notesCount = "Notes"
    open val learned = "Learned"
    open val share = "Share"
    open val addNote = "Add note"
    open val addNotes = "Add notes"
    open val createFirstNote = "Create your first note"
    open val nothingToStudy = "Nothing to study until tomorrow."
    open val viewNotes = "View all notes"
    open val subdecks = "Sub-decks"
    open val newShort = "New"
    open val learnInOrder = "Learn in order"
    open val readOnlyDeck = "Shared with you to study. Copy it to change it."
    open val deleteDeckHint = "Its sub-decks and notes go to Recently deleted for 30 days."
    open val leaveHint = "It disappears from your decks. Ask to be invited again to come back."
    open val searchLanguages = "Search languages"
    open val fewerReviews = "Fewer reviews"
    open val rememberMore = "Remember more"
    fun studyN(n: Int) = "Study $n"
    fun unlockAfter(percent: Int, deck: String) = "$percent% of $deck"
    fun counts(new: Int, learning: Int, review: Int) = "$new new · $learning learning · $review to review"

    // Sharing
    open val members = "People"
    open val owner = "Owner"
    open val viewer = "Can study"
    open val editor = "Can edit"
    open val invite = "Invite"
    open val inviteByEmail = "Invite by email"
    open val email = "Email"
    open val link = "Link"
    open val createLink = "Create a link"
    open val linkHint = "Anyone with the link can join. It works for 7 days."
    open val copyLink = "Copy link"
    open val copied = "Copied"
    open val revoke = "Revoke"
    open val remove = "Remove"
    open val pending = "Invited"
    open val publish = "Publish to Discover"
    open val published = "On Discover"
    open val editorsNeedPro = "Letting others edit needs Pro."
    open val shareOffline = "Sharing needs a connection."
    open val send = "Send"
    open val revokeTitle = "Withdraw this invitation?"
    open val revokeHint = "Its link stops working."
    open val removeHint = "The deck disappears from their decks. Their progress is kept in case they come back."
    open val someone = "Someone without a name yet"
    fun removeTitle(name: String?) = if (name == null) "Remove them?" else "Remove $name?"
    fun followers(n: Int) = if (n == 1) "1 follower" else "$n followers"

    // Study
    open val showAnswer = "Show answer"
    open val again = "Again"
    open val hard = "Hard"
    open val good = "Good"
    open val easy = "Easy"
    open val typeAnswer = "Type the answer"
    open val correct = "Correct"
    open val notQuite = "Not quite"
    open val finished = "All done for now"
    open val finishedHint = "Come back later for more."
    open val suspend = "Suspend"
    open val unsuspend = "Unsuspend"
    open val bury = "Hide until tomorrow"
    open val mark = "Mark"
    open val unmark = "Remove mark"
    open val marked = "Marked"
    open val editCard = "Edit note"
    open val space = "Space"
    open val progress = "Progress"
    open val nicelyDone = "Nicely done"
    open val speak = "Read aloud"
    open val play = "Play"
    open val missingMedia = "This file isn't on this device yet."
    fun studied(n: Int) = if (n == 1) "1 card studied" else "$n cards studied"
    fun left(n: Int) = "$n left"

    /** How long until a card comes back, short: 10m, 4h, 3d, 2.5mo, 1.2y. */
    fun interval(ms: Double): String {
        val minutes = ms / 60_000

        // One decimal below ten: 2.5mo, but 14d.
        fun one(v: Double): String {
            if (v >= 10) return v.roundToLong().toString()
            return ((v * 10).roundToLong() / 10.0).toString().removeSuffix(".0")
        }
        return when {
            minutes < 1 -> "<1m"
            minutes < 60 -> "${minutes.roundToLong()}m"
            minutes < 1440 -> "${(minutes / 60).roundToLong()}h"
            minutes < 1440 * 30 -> "${(minutes / 1440).roundToLong()}d"
            minutes < 1440 * 365 -> "${one(minutes / 43_800)}mo"
            else -> "${one(minutes / 525_600)}y"
        }
    }

    // Editor
    open val newNote = "New note"
    open val editNote = "Edit note"
    open val deck = "Deck"
    open val template = "Type"
    open val image = "Image"
    open val audio = "Audio"
    open val chooseAudio = "Choose audio"
    open val record = "Record"
    open val drawMasks = "Drag on the image to hide parts of it."
    open val clearMasks = "Clear masks"
    open val added = "Added"
    open val makeDeckFirst = "Make a deck first."
    open val addPicture = "Add a picture, then drag boxes over what to hide."
    open val makeBlank = "Select some words and choose Cloze to hide them."
    open val seeThem = "See them"
    open val cardsItMakes = "The cards this makes"
    open val deleteNoteHint = "It goes to Recently deleted for 30 days."
    open val dropFile = "or drop a file here"
    open val replace = "Replace"
    open val stop = "Stop"
    open val noMicrophone = "Rondo can't use the microphone. Allow it in the browser's settings."
    fun fillIn(field: String) = "Fill in “$field” to make a card."
    fun makes(n: Int) = if (n == 1) "Makes 1 card." else "Makes $n cards."
    open val ankiReadOnly = "This note keeps Anki's format, so it can't be edited here. Convert the deck to edit it."
    open val cloze = "Cloze"
    open val clozeHintLabel = "Hint, shown in the blank"
    open val showAgain = "Show it again"
    open val math = "Math"
    open val ruby = "Reading"
    open val table = "Table"
    open val bold = "Bold"
    open val italic = "Italic"
    open val underline = "Underline"
    open val highlight = "Highlight"
    open val subscript = "Subscript"
    open val superscript = "Superscript"
    open val codeMark = "Code"
    open val list = "List"
    open val numberedList = "Numbered list"
    fun cards(n: Int) = if (n == 1) "1 card" else "$n cards"

    // Template builder
    open val newTemplate = "New type"
    open val whatKind = "What kind of card?"
    open val whatKindHint = "Pick a type. You can switch for each note."
    open val yourTypes = "Your types"
    open val addCustom = "Add custom type"
    open val addCustomHint = "Choose the fields and questions."
    open val startFrom = "Choose a starting point for your type."
    open val editType = "Edit type"
    open val questions = "Questions"
    open val bothWays = "Ask both ways"
    open val bothWaysHint = "Also show the answer and ask for the front."
    open val typeAnswerHint = "Type answers before seeing them."
    open val listening = "Listening"
    open val listeningHint = "Also play the sound on its own and ask what it says."
    open val inDeckLanguage = "In the deck's language"
    open val reverseCard = "Reverse"
    open val listeningCard = "Listen"
    open val text = "Text"
    open val everyCard = "Every card, block by block"
    fun addTo(front: Boolean) = if (front) "Add to the front" else "Add to the back"
    fun affects(n: Int) =
        if (n == 1) "1 note uses this type; changes apply to it." else "$n notes use this type; changes apply to all."
    fun copyOf(name: String) = "My $name"
    fun summary(template: String) = when (template) {
        app.rondo.core.Templates.BASIC -> "A question and its answer."
        app.rondo.core.Templates.REVERSE -> "Asked both ways round."
        app.rondo.core.Templates.TYPE -> "Type the answer before you see it."
        app.rondo.core.Templates.CLOZE -> "Hide words in a sentence."
        app.rondo.core.Templates.OCCLUSION -> "Cover parts of a picture."
        app.rondo.core.Templates.VOCABULARY -> "A word with its reading, meaning, sound and an example."
        else -> ""
    }
    open val fields = "Fields"
    open val field = "Field"
    open val addField = "Add field"
    open val cardsTitle = "Cards"
    open val addCard = "Add card"
    open val front = "Front"
    open val backSide = "Back"
    open val divider = "Divider"
    open val label = "Label"
    open val typein = "Type-in box"
    open val addBlock = "Add"
    open val oneCardEach = "One card per cloze or mask"
    open val small = "Small"
    open val normal = "Normal"
    open val large = "Large"
    open val preview = "Preview"
    open val duplicate = "Make a copy to edit"
    fun inUse(n: Int) = if (n == 1) "Used by 1 note" else "Used by $n notes"
    fun kind(kind: String) = when (kind) {
        "image" -> image
        "audio" -> audio
        "occlusion" -> "Image with masks"
        else -> "Text"
    }
    fun problem(code: String) = when (code) {
        "name" -> "Give it a name."
        "field count" -> "A type has 1 to 32 fields."
        "field ids" -> "Every field needs a name."
        "card count" -> "A type has 1 to 16 cards."
        "empty front" -> "Every card needs something on its front."
        "type-in field" -> "A type-in box needs a text field."
        "each with several cards" -> "One card per cloze works with a single card only."
        "each field" -> "Pick a text or image-with-masks field."
        else -> "Something here doesn't fit."
    }

    // Browse
    open val allDecks = "All decks"
    open val allTypes = "All types"
    open val anyState = "Any state"
    open val stateNew = "New"
    open val stateLearning = "Learning"
    open val stateReview = "Review"
    open val stateSuspended = "Suspended"
    open val reset = "Forget"
    open val resetHint = "What was learned is forgotten and they come back as new cards."
    open val noNotes = "No notes match."
    open val selectAll = "Select all"
    open val clear = "Clear"
    open val sort = "Sort"
    fun sortBy(sort: String) = when (sort) {
        "changed" -> "Recently changed"
        "due" -> "Due soonest"
        "alpha" -> "A–Z"
        else -> "Newest"
    }
    fun selected(n: Int) = "$n selected"

    // Import
    open val importTitle = "Import from Anki"
    open val importHint = "Choose a .apkg or .colpkg file exported from Anki."
    open val dropPackage = "Drop a .apkg or .colpkg file here, or choose one."
    open val translate = "Make it editable"
    open val translateHint =
        "Turns Anki's HTML into Rondo cards. Off keeps cards exactly as they look in Anki, read-only."
    open val withHistory = "Include review history"
    open val withHistoryHint = "Brings every past review, for insights and better scheduling."
    open val importing = "Importing…"
    open val importFailed = "That file isn't an Anki package Rondo can read."
    fun imported(notes: Int, media: Int) = "Imported $notes notes and $media media files."
    fun skipped(n: Int) =
        if (n == 1) "1 note didn't fit and was left out." else "$n notes didn't fit and were left out."

    // Discover
    open val discoverHint = "Decks people share for everyone."
    open val anyLanguage = "Any language"
    open val follow = "Follow"
    open val followHint = "Study it as it is; the author's changes keep coming."
    open val copyHint = "Your own copy to change freely. It doesn't get the author's updates."
    open val adding = "Adding it…"
    open val noMatches = "Nothing public matches that."
    open val nothingShared = "Nothing shared yet. Decks people make public show up here."
    open val following = "Following"
    open val samples = "Sample cards"
    open val nothingFound = "Nothing found."
    open val discoverOffline = "Discover needs a connection."
    fun notes(n: Int) = if (n == 1) "1 note" else "$n notes"
    fun by(name: String) = "by $name"

    // Invitations
    open val accept = "Join"
    open val notNow = "Not now"
    open val invitationGone = "This invitation was used, revoked or expired."
    fun invited(owner: String?, editor: Boolean) =
        (owner ?: "Someone") + " invited you to study this deck" + (if (editor) " and edit it with them." else ".")

    // Insights
    open val reviewsYear = "Reviews in the last year"
    open val trueRetention = "True retention"
    open val retentionInfo = "Reviews of learned cards answered correctly, last 30 days."
    open val retentionPending = "Measured after 10 reviews of learned cards in a month."
    open val less = "Less"
    open val moreShades = "More"
    open val forecast = "Due in the next 30 days"
    open val totalCards = "Cards"
    open val suspendedCards = "Suspended"
    open val minutes = "Minutes, last 30 days"
    fun streak(days: Int) = if (days == 1) "1 day streak" else "$days day streak"
    fun reviews(n: Int) = if (n == 1) "1 review" else "$n reviews"

    // Settings
    open val account = "Account"
    open val name = "Display name"
    open val nameHint = "Shown to people you share decks with."
    open val general = "General"
    open val appearance = "Appearance"
    open val studying = "Studying"
    open val library = "Library"
    open val plan = "Plan"
    open val learnMore = "Learn more"
    open val documentation = "Documentation"
    open val upgrade = "Upgrade to Pro"
    open val yourProfile = "Your profile"
    open val monthly = "Monthly"
    open val yearly = "Yearly"
    open val manage = "Manage subscription"
    open val currentPlan = "Current plan"
    open val freePlan = "Everything for studying on your own and with others: sync, Anki import, sharing and Discover."
    open val proEditors = "Let people edit decks you share"
    open val proAgents = "Connect AI assistants through Rondo"
    open val proStorage = "5 GB for pictures and sounds, instead of 200 MB"
    open val paid = "Thanks for subscribing! Pro can take a moment to show here."
    open val redeemed = "Code redeemed."
    open val grading = "Answer buttons"
    open val gradingHint = "Four say how well you knew it; two are quicker."
    open val fourButtons = "Again, Hard, Good, Easy"
    open val twoButtons = "Again, Good"
    open val theme = "Theme"
    open val system = "System"
    open val light = "Light"
    open val dark = "Dark"
    open val textSize = "Text size"
    open val textSizeHint = "How large cards are while you study."
    open val templatesHint = "The built-in types, and the ones you make."
    open val importDecksHint = "Decks exported from Anki, with their media and history."
    open val agents = "AI assistants"
    open val throughRondo = "Through Rondo"
    open val serverUrl = "Server URL"
    open val serverUrlHint = "Add it to Claude, ChatGPT or another MCP client, then sign in and allow it."
    open val agentsNeedPro = "Connecting through Rondo needs Pro."
    open val connected = "Connected"
    open val noAgents = "No assistants connected yet."
    open val disconnect = "Disconnect"
    open val disconnectHint = "It can't read or change your decks until you connect it again."
    open val onYourComputer = "On your computer"
    open val localAgent = "Keeps a copy of your decks on your computer and serves it to assistants there, on any plan."
    open val privacySettings = "Privacy"
    open val data = "Your data"
    open val export = "Export everything"
    open val exportHint = "A ZIP of your decks, notes, review history and media, sent to your email."
    open val exportAction = "Export"
    open val exportSent = "We'll email you a link to your data shortly."
    open val signOutHint = "This device forgets your decks; they stay in your account."
    open val dangerZone = "Danger zone"
    open val deleteAccount = "Delete account"
    open val deleteWarning =
        "Deletes your account and everything in it. Decks others borrowed stay with them, without your name."
    fun proUntil(date: String) = "Pro until $date"
    fun renewsOn(date: String) = "Renews on $date"
    fun connectedOn(date: String) = "Connected $date"
    fun disconnectTitle(agent: String) = "Disconnect $agent?"

    /** Where Pro came from, when it isn't a subscription managed here: a store, a code or a gift. */
    fun proSource(provider: String?) = when (provider) {
        "app-store" -> "Bought in the App Store: change or cancel it there."
        "google-play" -> "Bought on Google Play: change or cancel it there."
        "promo" -> "From a promo code."
        "grant" -> "A gift from Rondo."
        else -> null
    }

    // Sign-in
    open val signInTitle = "Sign in to Rondo"
    open val signInHint = "Sync your decks, share them and use Rondo anywhere. New here? This makes your account."
    open val continueEmail = "Continue with email"
    open val code = "Code"
    open val codeSent = "We sent a code to"
    open val usePasskey = "Use a passkey"
    open val apple = "Continue with Apple"
    open val withoutAccount = "Rondo works without an account; your decks stay on this device."
    open val continueWithout = "Continue without an account"
    open val checkEmail = "Check your email"
    open val resend = "Send a new code"
    open val otherEmail = "Use another email"
    open val agreeTo = "By continuing you agree to the"
    open val terms = "Terms"
    open val and = "and the"
    open val privacy = "Privacy Policy"
    fun resendIn(seconds: Int) = "New code in ${seconds}s"

    // Consent
    open val consentTitle = "Allow access to Rondo?"
    open val allow = "Allow"
    open val deny = "Deny"
    fun wantsAccess(client: String) = "$client wants to read and change your decks and notes."

    // Sync issues
    open val issuesHint = "These changes couldn't be saved on the server."
    open val keepCopy = "Save my version as a copy"
    open val discard = "Discard"
    open val noIssues = "No sync issues."
    open val recovered = "Recovered"

    // Notifications
    open val gotIt = "Got it"

    // Profiles
    open val setupTitle = "Your profile"
    open val setupHint = "How people see you when you share decks. You can change it any time in Settings."
    open val username = "Username"
    open val usernameHint = "Your address: rondo.matthewsource.com/u/…"
    open val displayName = "Display name"
    open val displayNameHint = "In any language. Leave it empty to go by your username."
    open val flag = "Flag"
    open val noFlag = "No flag"
    open val looksGood = "Looks good"
    open val editProfile = "Edit profile"
    open val viewProfile = "View profile"
    open val hideActivity = "Hide my activity"
    open val hideActivityHint = "Your reviews and streaks don't show on your profile."
    open val noProfile = "No one here"
    open val noProfileHint = "There's no profile at this address."
    open val publishedDecks = "Decks on Discover"
    open val noPublished = "No decks on Discover yet."
    open val activity = "Activity"
    open val reviewsAllTime = "Reviews"
    open val cardsLearned = "Cards learned"
    open val daysStudied = "Days studied"
    open val currentStreak = "Streak"
    open val longestStreak = "Longest streak"
    open val studyTime = "Time studied"
    fun memberSince(date: String) = "Joined $date"
    fun movedFrom(old: String) = "@$old is now this profile."
    fun days(n: Int) = if (n == 1) "1 day" else "$n days"
    fun hours(minutes: Int) = if (minutes < 60) "$minutes min" else "${minutes / 60} h ${minutes % 60} min"
    fun yearReviews(n: Int, year: Int) = (if (n == 1) "1 review" else "$n reviews") + " in $year"
    fun usernameChangesOn(date: String) = "You can change it again on $date."
    fun tryInstead(suggestion: String) = "Try @$suggestion"

    /** Why a username can't be had, from the server's reason. */
    fun usernameRefusal(reason: String) = when (reason) {
        "invalid" -> "3 to 20 lowercase letters, digits and _."
        "reserved" -> "That one's reserved."
        "taken" -> "That one's taken."
        "held" -> "That was someone's until recently."
        else -> "Pick another one."
    }

    // Staff
    open val staff = "Staff"
    open val showStaff = "Show staff tools"
    open val hideStaff = "Hide staff tools"
    open val staffLocked = "Staff tools need a sign-in with your passkey."
    open val confirmPasskey = "Confirm with passkey"
    open val team = "Team"
    open val log = "Log"
    open val rondoItself = "Rondo"
    open val undoReason = "Why undo it?"
    open val undone = "Undone"
    open val removeRole = "Remove role"
    open val grantRole = "Give a role"
    open val nothingLogged = "Nothing in the log yet."
    fun until(date: String) = "until $date"
    fun undoneBy(who: String, why: String?) = "Undone by $who" + (why?.let { ": $it" } ?: "")
    fun roleName(role: String) = when (role) {
        "owner" -> "Owner"
        "admin" -> "Admin"
        "moderator" -> "Moderator"
        "support" -> "Support"
        "curator" -> "Curator"
        else -> role
    }

    /** A staff reason, by key: what the person is told too. */
    fun reason(key: String) = when (key) {
        "spam" -> "Spam"
        "harassment" -> "Harassment"
        "hate" -> "Hate"
        "sexual" -> "Sexual content"
        "impersonation" -> "Impersonation"
        "copyright" -> "Copyright"
        "illegal" -> "Illegal content"
        "name" -> "Inappropriate name"
        "evasion" -> "Ban evasion"
        else -> "Other"
    }

    open val byName = "Name"
    open val byEmail = "Email"
    open val byAddress = "Address"
    open val searchPeople = "Username, name or id"
    open val searchEmail = "The email they sign in with"
    open val searchAddress = "An address, or a range like 203.0.113.0/24"
    open val nobodyFound = "Nobody found."
    open val rules = "Community rules"
    open val secondFactorDue = "Enter the code from your authenticator app to keep syncing."
    open val secondStepTitle = "One more step"
    open val secondStepHint = "Enter the code from your authenticator app."
    open val useRecoveryCode = "Use a recovery code"
    open val useAuthenticator = "Use the authenticator app"
    open val recoveryCode = "Recovery code"
    open val lostAuthenticator = "Lost your authenticator?"
    open val lostTitle = "Remove the second step"
    open val lostHint =
        "We email you a code. Once you enter it, the second step is removed a week later, so a stranger can't."
    open val lostSentTitle = "It's removed in a week"
    open val lostSentHint = "Until then, signing in with the authenticator app or a recovery code cancels it."
    open val sendCode = "Send a code"
    open val security = "Security"
    open val signInMethods = "Ways to sign in"
    open val change = "Change"
    open val passkeys = "Passkeys"
    open val addPasskey = "Add a passkey"
    open val passkeyHint = "Sign in with your face, fingerprint or screen lock instead of a code."
    open val passkeyAdded = "Passkey added."
    open val linkedAccountHint = "Linked: you can sign in with it."
    open val linkAccountHint = "Link it to sign in with it too."
    open val secondStep = "Second step"
    open val recoveryCodesHint = "Each works once instead of the app. New ones replace the old."
    open val authenticator = "Authenticator app"
    open val authenticatorOn = "On: signing in asks for a code from it."
    open val authenticatorOff = "Off. Turn it on so a stolen email isn't enough to get in."
    open val passkeyEnough = "A passkey protects you already; the app adds a step everywhere else."
    open val turnOn = "Turn on"
    open val turnOff = "Turn off"
    open val scanHint = "Scan this with your authenticator app, or type the key, then enter the code it shows."
    open val recoveryCodes = "Recovery codes"
    open val recoveryHint =
        "Each works once instead of the authenticator app. Keep them somewhere safe; they won't be shown again."
    open val newCodes = "New recovery codes"
    open val savedThem = "I've saved them"
    open val devices = "Signed in on"
    open val thisDevice = "This device"
    open val signOutOthers = "Sign out everywhere else"
    open val emailLabel = "Email"
    open val changeEmail = "Change email"
    open val newEmail = "New email"
    open val confirmEmail = "Enter the code we sent to"
    open val linked = "Linked accounts"
    open val linkGoogle = "Link Google"
    open val linkApple = "Link Apple"
    open val unlink = "Unlink"
    open val confirmIdentity = "Confirm it's you: enter the code we sent to your email."
    fun resetPending(date: String) = "Your second step will be removed on $date, as someone asked."
    open val cancelReset = "Cancel it"
    open val redeemTitle = "Redeem a code"
    open val redeemHint = "A code gives you Pro for a while. It starts when the Pro you have ends."
    open val redeemAction = "Redeem"
    open val codeLabel = "Code"
    open val promo = "Promo codes"
    open val newBatch = "Make codes"
    open val howMany = "How many"
    open val daysOfPro = "Days of Pro"
    open val usableFor = "Usable for"
    open val noEnd = "No end"
    open val batchNote = "Note for staff"
    open val copyUnused = "Copy unused codes"
    open val unused = "Unused"
    open val revoked = "Revoked"
    open val grantPro = "Grant Pro"
    open val noBatches = "No codes yet."
    fun proFrom(date: String) = "You have Pro until $date."
    fun usedCodes(used: Int, of: Int) = "$used of $of used"
    fun usedBy(who: String, date: String) = "$who · $date"
    open val reminders = "Reminders"
    open val remindersHint = "Once a day at your time, when cards are due and you haven't studied yet."
    open val dailyReminder = "Daily reminder"
    open val remindAt = "Remind me at"
    open val remindHere = "On this device"
    open val remindByEmail = "By email"
    open val remindersBlocked = "Notifications are blocked here. Allow them in your browser or system settings."
    open val remindersImpossible = "This device can't show notifications."
    fun reminderTitle(cards: Int) = if (cards == 1) "1 card is waiting" else "$cards cards are waiting"
    open val reminderBody = "A few minutes keeps it all fresh."
    open val sortTop = "Top"
    open val sortNew = "New"
    open val sortHot = "Hot"
    open val report = "Report"
    open val reportTitle = "Report"
    open val reportWhat = "What's wrong?"
    open val reportWhichLaw = "Which law does it break?"
    open val reportWhy = "Why is it illegal? Where exactly is it?"
    open val reportDetails = "Anything that helps (optional)"
    open val reportGoodFaith = "I believe this report is accurate and complete."
    open val reportSent = "Thanks. Moderators will look at it."
    open val cases = "Cases"
    open val allLanes = "All"
    open val noCases = "Nothing needs a look right now."
    open val dismiss = "Dismiss"
    open val dismissHint = "Nothing to act on. These reports will count for less next time."
    open val reportsLabel = "Reports"
    open val reporters = "Reporters"
    open val people = "People"
    open val resolved = "Resolved"
    open val weightLabel = "weight"
    open val actOnSelected = "Act on the selected"
    fun reportCount(n: Int) = if (n == 1) "1 report" else "$n reports"
    fun reportReason(key: String) = when (key) {
        "spam" -> "Spam"
        "harassment" -> "Harassment"
        "hate" -> "Hate"
        "sexual" -> "Sexual content"
        "impersonation" -> "Impersonation"
        "illegal" -> "Illegal content"
        else -> "Something else"
    }
    fun law(key: String) = when (key) {
        "copyright" -> "Copyright"
        "child_safety" -> "Child safety"
        "terrorism" -> "Terrorist content"
        "privacy" -> "Privacy and personal data"
        else -> "Another law"
    }
    fun lane(key: String) = when (key) {
        "illegal" -> "Illegal"
        "safety" -> "Safety"
        "spam" -> "Spam"
        "waves" -> "Waves"
        "flags" -> "Flags"
        else -> "Other"
    }

    /** What a wave measured, or the rule behind a flag, in words. */
    fun caseSummary(kind: String, summary: String?, today: Int?, usual: Double?): String? = when (kind) {
        "wave" -> wave(summary, today ?: 0, kotlin.math.round(usual ?: 0.0).toInt())
        "flag" -> flagRule(summary)
        else -> null
    }

    private fun wave(metric: String?, today: Int, usual: Int): String {
        val what = when (metric) {
            "reports" -> "reports"
            "publications" -> "decks published"
            else -> "new accounts"
        }
        return "$today $what in a day; usually $usual"
    }

    private fun flagRule(rule: String?) = when (rule) {
        "new_account_publishing" -> "A day-old account published more than three decks"
        "address_publishing" -> "Five or more decks published from one address in a day"
        else -> rule
    }
    open val moderate = "Moderate"
    open val moderation = "Moderation"
    open val warn = "Warn"
    open val restrict = "Restrict"
    open val ban = "Ban"
    open val lift = "Lift restrictions"
    open val resetName = "Reset name"
    open val reasonLabel = "Reason"
    open val noteLabel = "Note"
    open val noteHint = "They see it, with the reason."
    open val howLong = "For"
    open val forGood = "For good"
    open val suggested = "Suggested"
    open val removeFromDiscover = "Remove from Discover"
    open val takeDown = "Also stop sharing it"
    open val takeDownHint = "People who follow it lose it. For illegal content and copyright."
    open val history = "History"
    open val privateDetails = "Private details"
    open val signsInWith = "Signs in with"
    open val addresses = "Addresses"
    open val pastNames = "Names"
    open val related = "Related accounts"
    open val noRelated = "No related accounts."
    open val billingLabel = "Billing"
    open val restrictAddress = "Restrict address"
    open val unverified = "unverified"
    open val roles = "Roles"
    fun forDays(n: Int) = if (n == 1) "1 day" else "$n days"
    fun restrictedUntil(date: String?) = if (date == null) "Restricted for good" else "Restricted until $date"
    fun bannedUntil(date: String?) = if (date == null) "Banned for good" else "Banned until $date"
    fun recentSteps(n: Int) = if (n == 1) "1 step in the last 180 days" else "$n steps in the last 180 days"
    fun why(reason: String) = when (reason) {
        "address" -> "same address"
        "email" -> "same inbox"
        "name" -> "similar name"
        else -> reason
    }
    fun moderationKind(kind: String) = when (kind) {
        "user.warn" -> warn
        "user.restrict" -> restrict
        "user.ban" -> ban
        "user.lift" -> lift
        "user.rename" -> resetName
        else -> kind
    }

    /** Your own restriction, where it stops you. */
    fun youreRestricted(date: String?) =
        (if (date == null) "Your account is restricted for good" else "Your account is restricted until $date") +
            ": you can't publish, share, invite or change your name."
    open val removedFromDiscover =
        "Moderators took this deck off Discover. It stays yours, and you can share it privately."

    private fun removal(takenDown: Boolean, deck: String) =
        (if (takenDown) "Took down" else "Removed from Discover") + " “$deck”"

    /** One entry of the staff log, in words: what was done to [who] (or [deck]). */
    fun action(kind: String, data: Map<String, String>, who: String, deck: String?): String = when (kind) {
        "role.grant" -> "Made $who ${roleName(data["role"].orEmpty()).lowercase()}"
        "role.revoke" -> "Took ${roleName(data["role"].orEmpty()).lowercase()} from $who"
        "staff.freeze" -> "Froze $who's staff powers: over the hourly limit"
        "user.warn" -> "Warned $who"
        "user.restrict" -> "Restricted $who"
        "user.ban" -> "Banned $who"
        "user.lift" -> "Lifted $who's restrictions"
        "user.rename" -> "Reset the name of ${data["from"]?.let { "@$it" } ?: who}"
        "deck.remove" -> removal(data["take_down"] == "true", deck ?: data["deck"].orEmpty())
        "network.restrict" -> "Restricted ${data["range"].orEmpty()}"
        "promo.batch" -> "Made ${data["count"]} codes for ${data["days"]} days of Pro"
        "promo.revoke" -> "Revoked code ${data["code"].orEmpty()}"
        "pro.grant" -> "Granted $who Pro"
        "case.dismiss" -> "Dismissed a case"
        else -> kind
    }

    /** Why something was refused, by error code. */
    fun error(code: String?): String = when (code) {
        "unauthorized" -> "Sign in first."
        "forbidden" -> "You can't change that."
        "read_only" -> "That's read-only now."
        "not_found" -> "That doesn't exist any more."
        "owner_mismatch", "cycle" -> "That move doesn't fit."
        "invalid" -> "Something in that isn't valid."
        "template_in_use" -> "Notes still use this type."
        "quota_exceeded" -> "Your media storage is full."
        "too_large" -> "That file is too large."
        "clock_ahead" -> clock
        "client_outdated" -> outdated
        "pro_required" -> "That needs Pro."
        "name_required" -> "Set a display name first, so people know who's sharing."
        "reauthenticate" -> "Confirm it's you first."
        "conflict" -> "That was changed elsewhere. Try again."
        "passkey_required" -> "Confirm it's you with your passkey first."
        "frozen" -> "Your staff powers are frozen: that's more than an hour allows."
        "second_factor_required" -> "Enter the code from your authenticator app."
        "no_passkey" -> "Add a passkey in Settings › Security first."
        "username_taken" -> "That username is taken."
        "username_invalid" -> "That username won't work. Pick another."
        "too_soon" -> "You can change your username once a month."
        "profile_required" -> "Set up your profile first, so people know who's sharing."
        "unavailable" -> "That isn't available right now."
        "offline" -> "You're offline."
        "no_account", "failed" -> "Signing in didn't work. Try again."
        "suspended" -> "This account is suspended. We emailed you why."
        "restricted" -> "Your account is restricted: you can't publish, share, invite or change your name."
        "network_restricted" -> "Sharing isn't available from your network right now."
        "code_invalid" -> "That code doesn't work."
        "already_pro" -> "You have Pro already, and it renews."
        "rate_limited" -> "That's a lot at once. Try again in a while."
        "wrong_code" -> "That code isn't right, or it expired."
        "expired" -> "That took too long. Start again."
        "cancelled" -> "Cancelled."
        else -> "Something went wrong. Try again."
    }
}

/** The strings in use. */
@JsExport
val strings: Strings = Strings()
